### ISSUE TITLE
Master Password - Cannot use paste to input the password

### ISSUE THREAD

**Issue by Soraph** [ramboxapp/community-edition#1925] opened 2018-10-25 07:17 UTC
### Steps to reproduce

1. Copy secure master password from password storage application
2. Open rambox
3. Try to paste the password

### Expected behavior

I should be able to paste the password without having to paste it somewhere else, therefore expose it to everyone around me.

### Actual behavior

I've to manually type the master password each time because the paste feature is disabled.

### ENVIRONMENT

Version: 0.6.2
Platform: darwin (x64)
Electron: 2.0.8
Chromium: 61.0.3163.100
Node: 8.9.3

**Comment by Ash258** [comment] 2018-10-25 09:18
Duplicate of #1439

**Closed by Ash258** 2018-10-25 09:18 UTC
