### ISSUE TITLE
cant copy inside rambox

### ISSUE THREAD

**Issue by hasbimuharip** [ramboxapp/community-edition#2487] opened 2019-11-23 14:15 UTC
Whenever i try to copy some text inside rambox ( e.g slack) and try to paste it in some text editor like notepad ++ it copies something weird like:

>  Ready
> 
>  Ready
> 
>  Ready
> 
>  Ready
> 
>  Ready
> 
>  Ready

	
	-
	> Rambox 0.7.2
	> Electron 7.1.1
	> win32 x64 10.0.18362

**Comment by pdecat** [comment] 2019-11-25 13:32
Dupe of https://github.com/ramboxapp/community-edition/issues/2469

**Closed** 2019-11-29 16:30 UTC
Labels: duplicate
