### ISSUE TITLE
cant see the bottom of my screen

### ISSUE THREAD

**Issue by weinstok** [ramboxapp/community-edition#1874] opened 2018-10-03 05:31 UTC
in all my apps that inside of rambox, I cant see the bottom of the screen (where you usually get the latest messages and the line were you write your message)

	
	-
	> Rambox 0.5.17
	> Electron 1.8.4
	> darwin x64 17.7.0

**Comment by JoshuaJarman** [comment] 2018-10-03 18:30
the bottom and right side of all my services screens are unreachable, the viewport doesn't match the actual viewport and there doesn't seem to be any way to reset it.  this is related to the persistent zoom bugs, the zoon and viewport handling is very problem prone and always going sideways with very little control to adjust or fix once it does.

**Comment by Ash258** [comment] 2018-10-03 18:32
Duplicate of #1308

**Comment by Ash258** [comment] 2018-10-03 18:32
See: https://github.com/ramboxapp/community-edition/issues/1308#issuecomment-407213251

**Closed by Ash258** 2018-10-03 18:32 UTC
