### ISSUE TITLE
Windows Ctrl + C shortcut not working

### ISSUE THREAD

**Issue by mwhelchel** [ramboxapp/community-edition#2510] opened 2019-12-03 03:17 UTC
Pressing "Ctrl + C" then pasting produces the following:

>  Ready
> 
>  Ready
> 
>  Ready
> 
>  Ready
> 
>  Ready
> 
>  Ready
> 
>  Ready
> You have the latest version of Rambox.

Right-clicking "Copy", then pasting works correctly.

	
	-
	> Rambox 0.7.2
	> Electron 7.1.1
	> win32 x64 10.0.17763

**Comment by bertyhell** [comment] 2019-12-03 10:46
duplicate of: https://github.com/ramboxapp/community-edition/issues/2469

**Closed** 2019-12-06 13:38 UTC
Labels: duplicate
