### ISSUE TITLE
Copy & Paste: Ready

### ISSUE THREAD

**Issue by schousda** [ramboxapp/community-edition#2534] opened 2019-12-24 16:13 UTC
When i copy some text in any App inside Rambox and paste it back, i only get the text "Ready"

### Steps to reproduce

1. Copy some text, for example from an Outlook email
2. Paste it back into an new email

### Expected behavior

I get the copied text.

### Actual behavior
I get the text "Ready" for multiple times.

### ENVIRONMENT

Rambox: v0.7.3
OS: Windows 10 x64 1909

**Comment by fvulich** [comment] 2019-12-27 14:53
I only can reproduce this error pressing Ctrl + A when the status bar has focus and press Ctrl + C 
![image](https://user-images.githubusercontent.com/46904390/71521382-50479100-289f-11ea-94bf-649588725e7d.png)
Please, if happens in other scenario please share it with.
We need more data in order to get a proper fix.

**Comment by goldensynaxis** [comment] 2020-01-10 00:16
I've started running into this in v0.7.3 pretty consistently.  Steps to reproduce:

* Highlight anything in Rambox using the mouse
* Make sure the status box is closed in the current tab, however the status bar must be open on a different tab
* Copy using Ctrl + C (haven't tested on a Mac yet)
* Paste using Ctrl + V.  Pasted content will show "Ready" for each tab which has the status bar
* Go to another other tab.  The "Ready" text is highlighted, despite not being the active tab.

Some things to note:
* If no tab has the Status bar, Ctrl + C doesn't copy any content at all
* If you right click, and copy the text using the mouse, it copies the correct content.

My gut feeling is that somehow the "Ctrl" button is causing Rambox to steal the focus.  I'm still not sure how the other tab's content is being selected, since I'm highlighting using the mouse.

**Comment by fvulich** [comment] 2020-01-10 14:35
Thanks for the feedback. Please share with us all the information that seems relevant for you.

**Closed** 2020-01-10 15:00 UTC
Labels: more-information-needed
