### ISSUE TITLE
Keyboard shortcuts for switching tabs failing

### ISSUE THREAD

**Issue by seaus66** [ramboxapp/community-edition#2159] opened 2019-03-19 03:04 UTC
### Steps to reproduce

1. Try using CTRL-TAB or CTRL-SHIFT-TAB and it fails

### Expected behavior
Switch tabs

### Actual behavior
Nothing happens

### ENVIRONMENT
Version: 0.6.4
Platform: win32 (x64)
Electron: 3.1.4
Chromium: 66.0.3359.181
Node: 10.2.0

**Comment by ishovkun** [comment] 2019-03-19 06:39
Same for me on Linux. Ctrl+number keys aren't working either.

**Comment by marklahn** [comment] 2019-03-19 07:30
I used to switch tabs with CTRL+PageUp/Down, and that no longer works either - 100% same environment as you.

I can get the shortcut to work ONCE, straight after I close the "about Rambox" popup, so the feature seems to be there, but some hook event is not working correctly?

**Comment by marklahn** [comment] 2019-03-19 08:55
Duplicate of https://github.com/ramboxapp/community-edition/issues/2125

**Comment by maxerbox** [comment] 2019-03-19 21:23
Fixed in #2138
@seaus66 pls close

**Comment by maxerbox** [comment] 2019-03-21 17:37
Fixed pageup-pagedown-zoomin-zoomout issue

**Closed** 2019-03-25 18:29 UTC
