### ISSUE TITLE
Copying with CTRL+C results in "READY READY READY READY..."

### ISSUE THREAD

**Issue by punkr0ck** [ramboxapp/community-edition#2469] opened 2019-11-21 12:07 UTC
Version: 0.7.1
Platform: win32 (x64)
Electron: 7.1.1
Chromium: 78.0.3904.99
Node: 12.8.1

If I copy text from any app (Discord, Slack,...) and paste it, the result is this:

```
 Ready

 Ready

 Ready

 Ready

 Ready

 Ready

 Ready
```

But if I copy the text by right-click -> copy then it works. Sometimes. for what ever reason it also works with CTRL+C but I've no idea why it fails most times. I also restarted Rambox.

**Comment by fvulich** [comment] 2019-11-21 17:42
We released 0.7.2 could you check if your issue is solved?

**Comment by flplatet** [comment] 2019-11-21 19:50
0.7.2 doesn't solve the issue.

**Comment by torrobinson** [comment] 2019-11-21 23:02
I thought I was going crazy! Just upgraded to 0.7.1 today, and copying from any internal tab adds a "Ready" for each tab I have open, it seems.

**Comment by punkr0ck** [comment] 2019-11-22 08:22
@torrobinson yes, exactly. the number of tabs you have in rambox matches the number of "ready's" when copying. maybe this helps the devs to get to the root of the problem.

what is more weird. i just opened rambox the first time today. i copied text from discord (a message by some user in in some channel). it copied correct. then i copied text from the input field in discord (where you type your message) and copied it and it results again in READYREADYREADY... - after this: i copied the same text from the user that worked before. now it's not working anymore.

so no, @fvulich - not solved.

**Comment by fvulich** [comment] 2019-11-22 12:01
We're investigating this issue, all the information that seems relevant for you please share it with us.

**Comment by 0xCCD** [comment] 2019-11-26 10:32
As a side note, when I disable the option "Always display Status Bar" it starts to copying empty text with breaks `` instead of those Ready's for me

```





```

**Comment by 0xCCD** [comment] 2019-11-26 10:41
Also it looks like the status bar text is selected once the copy scope changes

**Comment by 0xCCD** [comment] 2019-11-26 10:54
When you press Ctrl + A within the message box it selects all your written text and additionally the text within the status bar including the popup message "closing statusbar until next time" (if you hover your mouse over the X)

**Comment by pdecat** [comment] 2019-11-26 17:52
Furthermore, the issue only seems to happen after `Ctrl + A` has been pressed for the first time since the last reloading.
When it happens, reloading the tab resolves the issue until `Ctrl + A` is pressed again.

**Comment by pdecat** [comment] 2019-11-26 18:05
I can only reproduce the issue when a text input field has the focus and  `Ctrl + A` is pressed.
Pressing `Ctrl + A` when the focus is outside of any input field does not trigger the issue.

**Comment by JDHannan** [comment] 2019-11-26 18:45
I also have this problem. It doesn't happen 100% of the time, I got it to work by right-clicking and clicking Copy... that might not be the real issue though

**Comment by joaopsys** [comment] 2019-11-27 11:38
Exact same thing happening to me when I do CTRL+C, can only select, right click and copy.
CTRL+V pastes:

```
 Ready

 Ready

 Ready

 Ready

 Ready

 Ready

 Ready
```

**Comment by punkr0ck** [comment] 2019-11-27 12:05
another thing that i noticed: go to "Help -> About Rambox". It is marked if you previously copied text with CTRL+C. Now click in the About Rambox text to remove the marking. Then you will be able to copy one time with CTRL+C as it should be. After this the "About Rambo"-text is again marked by ghost hand. Maybe it's part of the root problem.

![grafik](https://user-images.githubusercontent.com/19614645/69721987-54ed1e00-1116-11ea-8884-36a30f151059.png)

**Comment by punkr0ck** [comment] 2019-11-27 12:07
another thing that i noticed: go to "Help -> About Rambox". It is marked if you previously copied text with CTRL+C. Now click in the About Rambox text to remove the marking. Then you will be able to copy one time with CTRL+C as it should be. After this the "About Rambo"-text is again marked by ghost hand. Maybe it's part of the root problem.

![grafik](https://user-images.githubusercontent.com/19614645/69722191-cc22b200-1116-11ea-89a2-d02505ae2b54.png)

**Comment by KrisGerhard** [comment] 2019-11-29 08:42
The application is pretty unusable on Windows due to this issue. :(

**Comment by flplatet** [comment] 2019-11-29 15:26
Ctrl+a selects also the main tab

![Selection_026](https://user-images.githubusercontent.com/38443518/69876900-bdf7a180-128e-11ea-8a85-ddcc370be6fe.png)

So far :
- right click + copy works fine. It's just a shortcut issue.
- ctrl+c doesn't copy the selected text in the focused service but some text from the Rambox app itself :
    - "Ready" from the status bar (bottom left), unless the option "Always display Status Bar" is disabled then there's to text to copy.
    - "Close statusbar until next time" when hovering the status bar X (bottom right)
    - the Rambox info when displayed (Help > About Rambox)
- the number of "Ready" matches the number of tabs

It seems the focus of the shortcuts is not the good one, it points to Rambox instead of the service.

**Comment by fvulich** [comment] 2019-11-29 16:29
It's been fixed in https://github.com/ramboxapp/community-edition/commit/906c997ccba45f80f15f90fa82e00a4d9e7e0361 It's gonna be part of our new release

**Comment by flplatet** [comment] 2019-11-29 16:37
Yeah \o/
Thanks

**Comment by KrystianGraba** [comment] 2019-12-01 00:19
I also have the same problem.

**Comment by pdecat** [comment] 2019-12-04 09:51
Custom built current master and can confirm the issue with Ctrl-C is fixed on Ubuntu.

**Comment by rekire** [comment] 2019-12-05 08:57
When is the next release? This is annoying as hell.

**Comment by fvulich** [comment] 2019-12-06 13:36
The new release with the fix is coming very soon!

**Comment by jakeb2c2** [comment] 2019-12-06 14:40
How soon is very soon? :)

**Comment by torrobinson** [comment] 2019-12-06 15:31
> How soon is very soon? :)

The team told me in a private, chat, let me paste to you what they said:

> READY READY READY READY READY READY READY 



Seriously I hope soon because sharing code with teammates is now a hilarious guessing game and involves accidentally yelling "READY" at people 😄

**Comment by NIXKnight** [comment] 2019-12-10 07:47
This is really a nasty bug.

**Comment by C-Nog** [comment] 2019-12-10 13:58
when the fix will come? its so annoying this bug ....almost migrating to STATION

**Comment by fnagel** [comment] 2019-12-10 16:57
This one is a dealbreaker -- even more than broken spellcheck.

**Comment by rekire** [comment] 2019-12-10 17:24
I'm READY for an alternative client without ads for a paid version

**Comment by JDHannan** [comment] 2019-12-10 17:29
> 
> 
> I'm READY for an alternative client without ads for a paid version

That's the most entitled comment I've read in a long time. Make me a better, free app! Don't even think about asking me to pay for it!

**Comment by rekire** [comment] 2019-12-10 17:51
I hate ads, I see absolutely no use in the paid version. Such an annoying bug for more then 2 weeks on production is a no go.

I didn't notice any new features since the pro version was introduced. However there were at least 4 updates. Bugs are normal but why was the update not simply reverted until the bug is fixed?

 Sorry if you don't like my honestly opinion.

**Comment by JDHannan** [comment] 2019-12-10 18:01
Don't translate "I'm an asshole" as "I'm being honest"

If you're not paying, you don't really get to complain.

**Comment by modo-lv** [comment] 2019-12-11 23:02
Appears to be fixed in 7.3.3.

**Comment by fvulich** [comment] 2019-12-12 12:51
Fixed in the 0.7.3. Thanks for the patience. :)

**Closed by fvulich** 2019-12-12 12:51 UTC
Labels: investigate

**Comment by Gabb1995** [comment] 2019-12-16 08:17
Just happened again for me on 0.7.3. I copied from a slack code snippet, ended up with 

 Ready

 Ready

 Ready

 Ready

**Comment by torrobinson** [comment] 2019-12-16 14:28
> Just happened again for me on 0.7.3. 

Confirmed: I copied some text and then tried to create a new Code Snippet, and when pasting into the Create Snippet modal,  I got the Ready text.

Then it started happening in the normal Slack's chat WYSIWYG editor.

The only thing that seems different now is that I'm getting some unicode unknown character boxes after each one (I don't recall seeing these before now):

![image](https://user-images.githubusercontent.com/4401999/70914595-88b0ba80-1fd5-11ea-8800-799d880cef24.png)
