### ISSUE TITLE
Can't install the 0.5.13 version on Fedora 26

### ISSUE THREAD

**Issue by johnnyasantoss** [ramboxapp/community-edition#1243] opened 2017-10-17 15:57 UTC
### Steps to reproduce

1. Get a fresh Fedora 26 installation
2. Download x64 rpm in GitHub releases of Rambox's repository.
3. Install and try to execute.

### Expected behavior

Open without errors

### Actual behavior

It fails with this error:
```bash
/opt/Rambox/rambox
/opt/Rambox/rambox: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory
```

### ENVIRONMENT

> Rambox: v0.5.13
> OS: Fedora 26
> Arch: x64

**Comment by bartmanus** [comment] 2017-10-27 10:18
Missing dynamically linked libraries on vanilla F27 beta install:
```$ cat /etc/redhat-release 
Fedora release 27 (Twenty Seven)
$ ldd /usr/local/bin/rambox | grep not\ found
	libnode.so => not found
	libXss.so.1 => not found
	libffmpeg.so => not found```

**Comment by diego-go** [comment] 2017-12-14 21:37
I got the same issue as @bartmanus, I already installed libXScrnSaver and nothing, still got the problem message:
`./rambox: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory`

**Comment by diego-go** [comment] 2017-12-14 21:46
I got the same issue as @bartmanus but finally I resolve it doing `pkcon install libXScrnSaver` and Rambox start well

**Comment by Ash258** [comment] 2018-09-01 21:07
Duplicate of #1035

**Closed by Ash258** 2018-09-01 21:07 UTC
