### ISSUE TITLE
Google Voice - Unable to Sign In

### ISSUE THREAD

**Issue by FallenSpaces** [ramboxapp/community-edition#2599] opened 2020-03-01 17:59 UTC
### Steps to reproduce

1. Add Google Voice into Tabs
2. Attempt Sign In

### Expected behavior

App will sign in and work normally.

### Actual behavior

Get error:

"This browser or app may not be secure. [Learn more](https://support.google.com/accounts/answer/7675428?hl=en)

Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in."

Following "Learn more" link gives two solutions:

1. Use supported browser (Chromium not listed here?)
2. Turn on Javascript in Chrome (Is this possible with custom code?)

### ENVIRONMENT

> Rambox: v0.7.3

> OS: Windows 10 - win32 (x64)

**Comment by BehindTheMath** [comment] 2020-03-03 15:13
This looks like a duplicate of #2557.

**Comment by fvulich** [comment] 2020-03-06 12:22
It will be fixed in our next release. duplicate of #2557

**Closed by fvulich** 2020-03-06 12:22 UTC
Labels: duplicate
