### ISSUE TITLE
gmail is not working with rambox 0.7.2

### ISSUE THREAD

**Issue by sairajdream** [ramboxapp/community-edition#2512] opened 2019-12-03 15:33 UTC
Hi everyone
I am trying to add gmail in my rambox but after putting my login details 
it is showing this error.

**"You are trying to sign in from a browser or app that doesn't allow us to keep your account secure.
Try using a different browser. Learn more"**

Any Idea how to resolve this issue?

![image](https://user-images.githubusercontent.com/58458782/70064912-4fa93b00-1610-11ea-84bb-0733c5ccda13.png)

	
	-
	> Rambox 0.7.2
	> Electron 7.1.1
	> linux x64 5.0.0-36-generic

**Comment by babastienne** [comment] 2019-12-04 12:29
Duplicate of #2495

**Closed** 2019-12-04 22:11 UTC
Labels: duplicate
