### ISSUE TITLE
Rambox dissapears after minimize Window (Windows)

### ISSUE THREAD

**Issue by rvansoest** [ramboxapp/community-edition#2253] opened 2019-05-02 06:52 UTC
### Steps to reproduce

1. Minimize Window
2. 
3. 

### Expected behavior

Application shows in taskbar

### Actual behavior

Rambox is not visible (still running according to taskmanager)

### ENVIRONMENT

> Rambox: v0.6.7

> OS: Microsoft Windows [Version 10.0.17763.437]

> Arch: win32 (x64)

**Comment by patrick7** [comment] 2019-05-02 08:20
Same issue here.

**Comment by kosi2801** [comment] 2019-05-02 10:11
Confirming the issue also for Rambox 0.6.7 on Linux Mint 18.3 64bit, Kernel 4.15.0-48-generic.
When trying to minimize Rambox, the window closes completely.

Upon reopening its position is also reset to the center of the leftmost screen (in multi-monitor setup) which is in my case NOT set as the primary display.

**Comment by pacstah** [comment] 2019-05-03 06:00
Same issue here, so it looks like it's not something on your machine only

**Comment by GuxMartin** [comment] 2019-05-03 17:52
Same in Rambox 0.6.7 on Ubuntu 18.10

**Comment by samwill** [comment] 2019-05-06 17:31
I am also seeing this on Rambox 0.6.7 Ubuntu 18.04

**Comment by Corchoneitor** [comment] 2019-05-06 18:52
Is this happening with any combination of "Display behavior" and "When closing the main window" configurations?

**Comment by rvansoest** [comment] 2019-05-07 06:46
> Is this happening with any combination of "Display behavior" and "When closing the main window" configurations?

That solved it. default behaviour has been changed. Set "when closing the main window" to keep in tray and/or taskbar.

**Comment by kosi2801** [comment] 2019-05-07 07:16
> That solved it. default behaviour has been changed. Set "when closing the main window" to keep in tray and/or taskbar.

Ok, I also managed to find a combination which keeps the window in the taskbar. Set Display behavior to "Show in Taskbar and Tray Icon" and When closing main window to "Keep in tray and/or taskbar". Thanks. But this is not intuitive though to have BOTH needed to be set this way and that it also affects the MINIMIZE action.

During that I found out that when I set Display behavior to "Show Tray Icon" and When closing main window to "Keep in tray and/or taskbar" the window closes and never comes up again when trying to "Show/Hide Window". The only way to remedy this (for me) is to stop and restart Rambox where it opens its window exactly once.

**Comment by ericzolf** [comment] 2019-05-13 06:42
I can confirm the behaviour on Fedora 29 under Gnome, exactly as @kosi2801 described it: either it's always open in the taskbar _and_ in the tray, or the window doesn't open when clicking on the tray icon. This appeared with version 0.6.7 and didn't show the behaviour before.

Also guessing that issues #2271, #2265, #2254 and #2256 are related.

**Comment by diego-betto** [comment] 2019-05-21 08:54
Same here Ubuntu 19.
`Display behaviour`
"Show in Tray" is useless, you cannot restore the window with "Show/Hide Window", it has no effect
If "Show in Taskbar*" is selected you cannot restore the window with "Show/Hide Window", it has the only effect to show/hide the app thumbnail from the ALT-TAB switch window. 

For me the only way to show the window again is to use "Show/Hide Window" from the taskbar, then use ALT-TAB to show app thumbnails and then click to Rambox one.

Or the combo
- Display behaviour: "Show in Taskbar"
- When closing: "Keep in tray and/or taskbar"
- ignore "Show/Hide Window", it has no effect
- only use ALT-TAB to show again the window

**Comment by marcelovital** [comment] 2019-05-24 17:57
Same here on RHEL 8. Even ALT-TABbing doesn't show the window who disappeared. But it's running and showing at the taskbar.

To reopen it I need to:
- Right-click taskbar icon
- "Show/Hide Window" (it actually "hides" the window that disappeared)
- Right-click taskbar icon
- "Show/Hide Window" (it "re-enables" the window that disappeared, but still doesn't show it)
- ALT-TAB to the Rambox window

**Comment by ericzolf** [comment] 2019-06-28 06:33
Issue still present in Rambox 0.6.9 on Fedora 30.

**Comment by 0Delfo0** [comment] 2019-08-10 21:25
Issue still present in Rambox 0.6.9 on Ubuntu 19.04.

**Comment by iamecc** [comment] 2019-09-21 00:46
Most fixes I found for that Rambox tray icon issue were done before compile/install by editing some Electon files. What I still couldn't find was a possible fix for **post**-installing - I'm running Rambox 0.6.9 under Linux Mint 19.2 amd64 with Cinnamon 4.2.4, installed from the 64-bit .deb package.
My current settings are below:

Display behaviour: show in taskbar and tray icon
When closing the main window: keep in tray and/or taskbar

This works, but I'd like to keep that on tray only, so I can save space on the Cinnamon taskbar.
What I'd like to use is:

Display behaviour: show tray icon
When closing the main window: keep in tray

Also, I'd like to toggle show/hide main window with a single click on the tray icon. If someone knows how to do that, please post it here.

**Comment by iamecc** [comment] 2019-09-23 01:13
So I just found something interesting right now. If I set Rambox to this:

```
Display behaviour: show in taskbar and tray icon
When closing the main window: keep in tray
```

every time I use "Show/hide window" on the tray icon so I want to show the window, the Rambox button appears on the taskbar, but the window keeps minimized. So is there some workaround to make it actually open the window instead of just showing the button on taskbar?

**Closed** 2019-11-07 14:22 UTC
Labels: bug
