### ISSUE TITLE
Google Voice Blocked (by Google)

### ISSUE THREAD

**Issue by 3rdEyeBall** [ramboxapp/community-edition#2605] opened 2020-03-05 22:12 UTC
-
	> Rambox 0.7.3
	> Electron 7.1.1
	> linux x64 5.5.4-050504-generic

**Comment by fvulich** [comment] 2020-03-06 12:22
It will be fixed in our next release. duplicate of #2557

**Closed by fvulich** 2020-03-06 12:22 UTC
Labels: duplicate
