### ISSUE TITLE
ctrl+c copies READY READY READY instead of selected text

### ISSUE THREAD

**Issue by propiro** [ramboxapp/community-edition#2513] opened 2019-12-03 23:07 UTC
Hello,
Rambox copies following text to clipboard:
"

 Ready

 Ready

 Ready

 Ready

 Ready

 Ready

 Ready
"
when ctrl+a, ctrl+c combination is pressed to copy all text. Happen more often on multi-line text than single line, but its not a rule.
Copying with mouse menu does not produce such effect.

	
	-
	> Rambox 0.7.2
	> Electron 7.1.1
	> win32 x64 6.1.7601

**Comment by mindbreaker** [comment] 2019-12-04 10:48
Duplicate of: https://github.com/ramboxapp/community-edition/issues/2469

**Closed** 2019-12-06 13:33 UTC
Labels: duplicate
