### ISSUE TITLE
Slack download links do not work same across machines

### ISSUE THREAD

**Issue by dare023** [ramboxapp/community-edition#1274] opened 2017-10-31 07:13 UTC
I found bit weird issue:
- on laptop if I want to download the file in Slack,  it is not possible to do so, unless the browser is fully logged in and Slack channel opened.
On desktop it just opens download window in browser.
Both systems:
Arch Linux 64
Chrome browser

**Comment by shakalandy** [comment] 2017-11-30 13:56
you have to re-login in the browser. 
Slack Feature?

**Comment by FlorianLudwig** [comment] 2018-04-26 19:14
I guess this is a duplicate of #380

**Closed** 2018-11-02 10:46 UTC
Labels: wontfix
