### ISSUE TITLE
rambox weird clipboard using slack service in linux

### ISSUE THREAD

**Issue by danielmotaleite** [ramboxapp/community-edition#1235] opened 2017-10-12 18:53 UTC
rambox keep injecting old data PRIMARY data using slack

This is a problem with linux clipboards, as it have 3 different clipboards:
CLIPBOARD - normal ctrl+c
PRIMARY - select text with mouse is copied automatically to this one
SECONDARY - not very used, is usually used to synchronize both clipboards and avoid auto-select fields from overwrite any existent clipboard in PRIMARY

clipboard managers usually synchronize this clipboards, but to replicate this problem, its easier without then as old data keeps showing up and makes hard to understand where the data come from

### Steps to reproduce

1. Install a linux, use fluxbox as window manager (probably other WM also fail, as long they do not have any clipboard manager)
2.  install rambox and add a slack service
3.  select some text with the mouse and press ctrl+c to copy (it will fill the CLIPBOARD buffer)
4. paste another app using middle click. Should print the copied text
5. go back to the rambox, select a text with the mouse (it should fill the PRIMARY buffer)
6. paste in another app, using the middle click. it should print the CLIPBOARD text
7. go back to rambox, select some other text, press ctrl+c
8. paste using middle click in another app, the original copied text show up again, new copy disappears

sometimes i can paste this last copy, but then clicking in rambox and then going back to paste it in external app will show the old clipboard content

this looks related with slack, i tried to replicate the problem with skype and it do works well.
selecting text to copy data to the PRIMARY do not work at all. ctrl+c works most of the time, but maybe due the PRIMARY (or even SECONDARY), it gets confused

### Expected behavior

ctrl+c should fill the CLIPBOARD
text select should fill the PRIMARY
every time rambox gains focus, it should not re-inject any CLIPBOARD or PRIMARY content

### Actual behavior

Its very confusing, but it looks like that every time rambox gain focus its updating the clipboards (clipboard, primary, or both) with what ever it may have. Using several slack services i keep pasting old data all the day, from some other slack service

### ENVIRONMENT

RAMBOX: 0.5.13
Platform: linux (x64)
Electron: 1.7.8
Chromium: 58.0.3029.110
Node: 7.9.0

 OS:  ubuntu 17.04, using fluxbox as windows manager
 Arch: x64

**Comment by danielmotaleite** [comment] 2017-10-12 19:12
notice that using Franz or plain slack client i do not have any issue

**Comment by zackse** [comment] 2017-10-13 19:38
FWIW, I'm seeing this with Slack alone in XFCE. It seems that clicking in the Slack window clears the PRIMARY clipboard and resets to the previous value in CLIPBOARD, which is incredibly frustrating when adding some formatting punctuation (e.g., backticks), pasting with the middle-mouse, and getting... old content.

**Comment by danielmotaleite** [comment] 2017-10-18 13:19
confirmed, i just updated the normal slack client, tested it and i found the same problem.
I reported to slack team and they replied that they have a possible internal fix being tested.

So the problems looks that is only from slack and not rambox

lets keep this open until the slack update is released

**Comment by pcarinhas** [comment] 2017-10-24 16:59
+Confirmed.. Running icewm in Debian9 with Slack client 2.8.1. This behaviour is extremely distruptive to workflow..

**Comment by hoelzro** [comment] 2017-10-25 21:52
Also confirmed running AwesomeWM on Arch

**Comment by Ahuri3** [comment] 2017-10-30 17:36
Confirmed with gnome on Arch

**Comment by zmichael** [comment] 2017-11-03 10:25
Confirmed with Kubuntu 17.04

**Comment by Boovov** [comment] 2017-11-05 22:49
I can confirm that this also happens on:  CentOS Linux release 7.4.1708 (Core)

[mike@vov ~]$ rpm -qa | grep slack                                                                                                
slack-2.8.1-0.1.fc21.x86_64

**Comment by kolombo** [comment] 2017-12-12 17:31
Observe this issue on Arch and XFCE
slack - 2.8.0-1 - Issue exists
slack - 2.6.3-1 - Works correctly

So downgraded for now and will not upgrade until it is fixed :)

**Comment by kolombo** [comment] 2017-12-13 07:46
This seems to be fixed in 3.0.0.1

**Comment by danielmotaleite** [comment] 2017-12-22 16:51
will be one rambox update to include slack 3.x so this can be fixed?

**Comment by danielmotaleite** [comment] 2018-03-02 16:02
So slack already fixed this, but rambox still have this problem... so @saenzramiro needs to update something on rambox to import the fix.

This problem is very annoying, as it mess up the copy&past of all machine apps every time we click on rambox

I also check the commit history and the only commit that i see that touch the clipboard/focus is 
https://github.com/saenzramiro/rambox/commit/ac6183fbb7dda9638202506b4d1734a65bacd396 ... maybe something related with this?

**Comment by hoelzro** [comment] 2018-03-02 19:47
This is indeed very frustrating, but @saenzramiro has the unenviable task of trying to figure out what Slack changed in their own proprietary client that fixes this.  It's not like he can just update a library or something.  I'm wondering if this is something that Electron kind of does on its own, and Rambox needs to explicitly suppress it?

**Comment by danielmotaleite** [comment] 2018-04-12 14:14
@saenzramiro , i contacted slack about this problem and they replied this:

> So, I've had a chat with our engineers about the fix that you were describing. While it's hard to say for certain that this will work for Rambox without seeing all of the relevant code, the change we made that *likely* fixed the issue was moving away from embedding Slack in a "webView" and instead using a "browserView": https://electronjs.org/docs/api/browser-view
> 
> I hope this helps, and if you have any further questions please let me know.

So i hope this helps getting this fixed!

Any questions i can forward to then

**Comment by klokop** [comment] 2018-09-28 09:16
Same thing is happening when using Whatsapp and Mattermost.

**Comment by danielmotaleite** [comment] 2018-10-31 14:22
this problem and variants are getting a blocker for many people that try rambox and abandon it soon after :(

**Closed** 2019-01-11 22:35 UTC
Labels: wontfix
