### ISSUE TITLE
Can't paste via CMD+V in macos

### ISSUE THREAD

**Issue by Bulletninja** [ramboxapp/community-edition#2170] opened 2019-03-21 23:21 UTC
### Steps to reproduce

1. Have some text copied
2. Open any rambox service (tested whatsapp, messenger, slack and twitter)
3. Focus on any textbox
3. CMD+V

### Expected behavior

Clipboard content should be pasted

### Actual behavior

Nothing is pasted

### ENVIRONMENT

Rambox: v0.6.4
Platform: darwin (x64)
Electron: 3.1.4
Chromium: 66.0.3359.181
Node: 10.2.0

---

Pasting only works if i right-click and paste. If i push CMD+V "Paste and match style" is selected and nothing ever gets pasted.

![Screen Shot 2019-03-21 at 4 19 20 PM 1](https://user-images.githubusercontent.com/71659/54790937-21580c80-4bf5-11e9-8476-ac04299bff87.jpg)

**Comment by ohcibi** [comment] 2019-03-25 10:31
Can't reproduce exactly. My paste is bound to cmd+v. But paste and match style also does not work.

**Comment by fvulich** [comment] 2019-03-27 13:35
Sadly it's an issue of the new version of electron that treats the webview like an iframe and some of the events don't get triggered anymore, we are working on a workaround that it's gonna be part of the new version.

**Comment by saenzramiro** [comment] 2019-04-15 21:32
This should be fixed in next version. If not, please reopen it. But for now, I will close it.

**Closed by saenzramiro** 2019-04-15 21:32 UTC
