### ISSUE TITLE
JS error when new mail notification appears

### ISSUE THREAD

**Issue by dzeidzei** [ramboxapp/community-edition#1849] opened 2018-09-05 05:40 UTC
### Steps to reproduce

1. Install Rambox and add gmail account
2. Receive new mail

### Expected behavior

Desktop notification about new mail appears.

### Actual behavior

Following error dialog appears every time new mail is received and is being notified:

A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from
C:\Users\xxxx\AppData\Local\Rambox\app-0.5.17\resources\app.asar\resources\icon.ico
at object.exports.setBadge
(C:\Users\xxxx\AppData\Local\Rambox\app-0.5.17\resources\app.asar\electron\tray.js:76:1
at updateBadge
(C:\Users\xxxx\AppData\Local\Rambox\app-0.S.17\resources\app.asar\electron\main.js:28...
at BrowserWindow.mainWindow.on
(C:\Users\xxxx\AppData\Local\Rambox\app-0.5.17\resources\app.asar\electron\main.j...:52)
at emitTwo (events.js:125:1 3)
at BrowserWindow.emit (events.js:213:7)
at WebContents.webContents.on
(C:\Users\xxxx\AppData\Local\Rambox\app-0.5.17\resources\electron.asar\browser\ap...:10)
at emitThree (events.js:1 35:1 3)
at WebContents.emit (events.js:216:7)

### ENVIRONMENT

Rambox: v0.5.17
OS: Windows 8.1
Arch: x64

**Comment by Ash258** [comment] 2018-09-05 06:49
Duplicate of #1848

**Closed by Ash258** 2018-09-05 06:49 UTC
