### ISSUE TITLE
"Show/Hide Window" option of Try icon's right-click menu does not work at all !

### ISSUE THREAD

**Issue by Nokia808** [ramboxapp/community-edition#2306] opened 2019-06-17 17:05 UTC
### Steps to reproduce

1. right click on Rambox' try icon
2. try, then to use "Show/Hide Window" option of right-click menu of Rambox' try icon

### Expected behavior

<Should work to show/hide Rambox window>

### Actual behavior

<Not work at all ! Only flash screen with voice, but no real switching !>

### ENVIRONMENT

<Cinnamon DE version 4.0.10>

> Rambox: v0.6.8

> OS: Fedora Linux

> Arch: x64

**Comment by AXeL-dev** [comment] 2019-06-17 20:08
I confirm this bug. It wasn't there before version 0.6.3 & more exactly before upgrading to electron 3 / 4.

**Comment by ericzolf** [comment] 2019-06-28 06:34
I guess it's a duplicate of  Rambox dissapears after minimize Window (Windows) #2253

**Comment by fvulich** [comment] 2020-03-09 21:33
I'm gonna close this ticket because seems to be fixed now, feel free to open another ticket if the problem persists.

**Closed by fvulich** 2020-03-09 21:33 UTC
Labels: bug, duplicate, linux
