### ISSUE TITLE
Microsoft Teams fails to load

### ISSUE THREAD

**Issue by JPaulMora** [ramboxapp/community-edition#2380] opened 2019-08-17 01:51 UTC
I've included the webpage logs, it loaded just fine the first time and reloading seems to break it.

Thanks
[teams.microsoft.com-1566006529406.log](https://github.com/ramboxapp/community-edition/files/3511539/teams.microsoft.com-1566006529406.log)

	> Rambox 0.6.9
	> Electron 4.1.4
	> darwin x64 18.6.0

**Comment by kosi2801** [comment] 2019-08-19 06:47
Ok, confirming issue is occuring since about a week.

### Steps to reproduce

1. Set up a Teams account
2. Close/shutdown Rambox
3. Restart Rambox
4. Switch to Teams tab and login if required

### Expected behavior

Teams shows up

### Actual behavior

Only white background displayed in tab. Teams not visible.

### ENVIRONMENT

> Rambox: v0.6.9
> OS: Linux Mint (5.0.0-23-generic)
> Arch: x64

**Comment by noxer** [comment] 2019-08-19 08:55
Some additional info

After a while (> 10 min) it displays an error page about problems to load Teams and offers to sign you out so you can sign in again. It does not help, though. Deleting the Teams tab and setting it up again helps until Rambox is restarted.

**Comment by noxer** [comment] 2019-08-19 09:20
This seems to be a duplicate of #2375

**Comment by pietrushnic** [comment] 2019-09-15 22:06
In developer console I see 3 warnings like this:

```
The FetchEvent for "https://teams.microsoft.com/_#/conversations/?ctx=chat" resulted in a network error response: a redirected response was used for a request whose redirect mode is not "follow".
```

**Comment by fhibler** [comment] 2019-09-19 07:40
Confirming this bug as well on OSX.

**Comment by ZEROF** [comment] 2019-09-25 16:20
HI,

Same here, white page. I think that you need to read this https://teams.microsoft.com/dl/launcher/attribution.txt, if not you can't use integration anymore.

**Comment by timeterror** [comment] 2019-09-27 06:01
Hi,

I've been experiencing the same issue, but have noticed that if I open the developer tools, _delete the cache_, disable the cache (default), and enforce the _Edge - Windows user agent_ that it seems to work without the need for removing the Teams tab. 
Reloading the tab a few times doesn't cause any issues, but sadly the problem does return as soon as the developer settings have been reset again. Luckily, the developer settings seem to linger for a single restart which requires this workaround only to be used every other restart (just be sure to keep the developer tools open until the teams tab has loaded).

**Comment by Tha-Fox** [comment] 2019-10-07 07:33
I have the same issue.
Rambox: v0.6.9
OS: Arch Linux
Arch: x64

I've also noticed that if you delete the cache and restart the app, the login works once, but not twice.

**Comment by m-s-** [comment] 2019-10-15 10:12
My routine is a bit simpler, based on the current waiting pull request:
- open developer tools for the Teams tab
- go to Application > Service Workers and Unregister
- Reload the tab

This way I don't lose the login information and can keep using it. Not sure if there's a way to inject a script to do this unregister step.

**Comment by noxer** [comment] 2019-10-15 10:26
You can also use the custom script
```
Object.defineProperty(navigator.serviceWorker,"register",{value:()=>Promise.reject()});
```
Source: https://github.com/ramboxapp/community-edition/issues/2347#issuecomment-530483570

**Comment by requiem240sx** [comment] 2019-10-16 20:26
I have had the same issue all month, we also have some very strict MFA (with okta) that I thought was the reason. Can confirm the above custom script fixed my issue, thank you very much! My sanity is restored!

**Comment by fvulich** [comment] 2019-11-05 22:35
https://github.com/ramboxapp/community-edition/commit/2de8e8e41b73ff2492813850b20f4bd5b0b46c3f

**Closed by fvulich** 2019-11-05 22:35 UTC

**Comment by kosli** [comment] 2019-11-22 09:57
Teams stopped working for me in 0.7.0 (and 0.7.1), even with the custom script applied, which worked before in 0.6.9 :-(

**Comment by ZEROF** [comment] 2019-11-22 10:01
Solution for Linux users:

1. Remove your Teams APP (you need to start over)
2.  rm -rf .config/Rambox/Partitions/teams_*/
3. Add Teams APP again

All working ok without script
