### ISSUE TITLE
"365" displayed in icon whenever I leave the app on Outlook 365

### ISSUE THREAD

**Issue by MJae** [ramboxapp/community-edition#1379] opened 2018-01-09 04:20 UTC
### Steps to reproduce

1. Open Rambox
2. Navigate to Outlook 365 tab

### Expected behavior

https://gyazo.com/a3936c6c7a1db397fe138bc1a4fcfeee

### Actual behavior

https://gyazo.com/415508b943b875e1669ca165bc35289b

### ENVIRONMENT

> Rambox: v0.5.13

> OS: Win10

> Arch: x64

**Comment by JakobStruye** [comment] 2018-01-09 13:43
Duplicate of #1131 , fixed in #1250 (not yet merged)
You can circumvent this for now by renaming the tab to something that doesn't contain "365" (or any other number).

**Comment by dan-v** [comment] 2018-01-09 19:56
@JakobStruye - thanks for the renaming tab tip - you made my day. Was just living with this annoyance until fix was merged.

**Comment by Ash258** [comment] 2018-01-19 16:12
@MJae Still encountering this issue in 0.5.14?

**Comment by MJae** [comment] 2018-01-20 09:01
Nope, not anymore.

I would like to confirm that this bug is no longer present after the update. I put "365" back in the tab name and it is no longer being recognized in the app icon as the unread counter.

**Closed** 2018-11-02 12:46 UTC
Labels: wontfix
