### ISSUE TITLE
Issue - Slack Audio Not Picking Up Microphone

### ISSUE THREAD

**Issue by ArtursO** [ramboxapp/community-edition#736] opened 2017-03-14 22:46 UTC
### Steps to reproduce

1. Make audio call out of slack while wearing a headset
2. 
3. 

### Expected behavior

Microphone from headset works

### Actual behavior

Microphone not being picked up by Slack / Rambox

### ENVIRONMENT

> Rambox: v0.5.3

> OS: macOS Sierra

> Arch: x64

**Comment by saenzramiro** [comment] 2017-04-03 17:09
Did you check if your sound configuration of your Mac are ok?

Because Rambox use the system defaults.

**Comment by SeanFelipe** [comment] 2017-10-12 17:21
Slack has been pretty sketchy for me as well. Sound configurations are fine on the mac -- I'm listening to audio through headphones, and other apps like zoom are picking up the mic just fine.

**Comment by michaelaleo** [comment] 2017-10-16 17:02
This happens to me all the time too. Latest MacOS. Get the yellow error bar saying it can't find an audio device, but input works great across all other apps.

If I connect a secondary audio device, then click the gear in the call, and select the new device, it works. Albeit with pretty rough quality—but I think that's a separate issue.

**Comment by SeanFelipe** [comment] 2017-10-16 18:20
FWIW, when I switch between audio input sources, when i select built-in microphone, the other party can hear me for about a second before it cuts out. If I switch away and back I get another blip of audio input.

**Comment by millzpaugh** [comment] 2017-10-19 20:07
I'm also having this problem, same OS.

**Comment by alexandergunnarson** [comment] 2017-10-30 15:09
To reproduce: with Slack started on MacOS Sierra (latest update), I insert my headphones (which don't have microphone capability) and start an audio call.

To quick-fix: I restart Slack.

To the makers of Slack: Your product is great. But please fix this. This happens to me every single day.

**Comment by foreground-voice** [comment] 2017-11-11 23:42
I have the same issue. My OS is Yosemite, and headset Sony DR-BTN200. When I start calling the ring 
 sounds in headset. But when my interlocutor got the call the sound of call move into OS internal. It's really annoying because Skype works well in same environment. Restart of Slack don't solves issue.

**Comment by myliu1999** [comment] 2017-11-14 04:14
I got the same issue too. macOS Sierra 10.12.6

**Comment by itsecurity-partnercomm** [comment] 2017-11-14 18:24
I have users who are experiencing this same issue, has anyone put in a ticket with Slack. If so, what was their response?

**Comment by myliu1999** [comment] 2017-11-16 06:36
BTW, my issue disappear after restarting slack.

**Comment by foreground-voice** [comment] 2017-11-20 10:25
After update the issue has gone. I got ability to change settings of call, selecting of headset mic and phones. Thanks to Slack's developers.

**Comment by MKBlackmer** [comment] 2018-04-17 16:31
which version of slack has this issue? I am currently experiencing the same problem.

**Comment by itsecurity-partnercomm** [comment] 2018-04-17 17:08
From what I can tell I have people who experience this on any version. All Slack told me to do was close and reopen until it worked.

**Comment by MatissJanis** [comment] 2018-05-24 08:45
I'm experiencing the same issue.

**Comment by redtailtara** [comment] 2018-05-25 18:16
me too :(

**Comment by latuprez** [comment] 2018-06-07 13:36
me too

**Comment by MajorSarg** [comment] 2018-06-12 15:36
I have the same problem on my mac. Google Hangouts works just fine for me so I am not sure its a configuration on my end. I hope they fix this soon.

**Comment by larbyamirouche** [comment] 2018-06-16 01:15
me too...

**Comment by fatboyslimfast** [comment] 2018-06-20 08:47
Same issue .. headphone/mic works on Skype call ... but only audio available on Slack call

**Comment by doktorstick** [comment] 2018-06-26 22:35
I have my Macbook connected to the Apple Display, which has the built-in microphone, speakers, and camera. The microphone is the only one of the three that is having problems; Slack uses the microphone on my Macbook. Since the laptop is closed, I'm very muffled to anyone I'm on a call with. I have to open the clamshell for them to hear me.

I searched through Slack settings looking for an option to choose the input; no such luck.

**Comment by russelljjarvis** [comment] 2018-07-05 18:48
I also have this problem under OSX. Microphone is picked up under other native applications. I agree that this issue might relate to waking after suspend, and not rebooting.

**Comment by yagizerkan** [comment] 2018-08-07 17:29
Same here. Shutting down Slack and restarting it didn't help when I tried it the last time. 

OS X 10.13.6 
Slack 3.2.0 (latest as of this writing)

**Comment by Blackbaud-AlexKingman** [comment] 2018-08-08 20:41
Same problem. OSX 10.13.6
Slack 3.3.0-beta1 master/a8488a9 (Beta)

**Comment by nuclearnic** [comment] 2018-08-20 08:51
I'm having the same problem too.
OSX 10.12.6
Slack 3.2.0

**Comment by kylepolich** [comment] 2018-08-22 16:53
Same problem.  Kind of embarrassing for Slack that it's been over a year with no fix.

**Comment by SeanFelipe** [comment] 2018-08-22 16:58
this has been happening intermittently for me and lately is fixed with a restart of the app.

osx 10.13.5, slack 3.2.0

**Comment by Ash258** [comment] 2018-08-22 17:15
What does native slack app have to do with Rambox??
This repo does not have anything to do with Slack application.

**Comment by Mentessi** [comment] 2018-08-28 16:34
Have had this issue for a while - only seems to happen on group/channel calls... direct calls is fine.
Slack 3.2.0
OSX 10.13.6

Annoying as hangouts & Skype work fine.

**Comment by Ash258** [comment] 2018-08-28 16:44
This is not repository for SLACK APPLICATION, but for RAMBOX application. 
We cannot do anything about official standalone Slack application. If you have problem with slack app go to report on their forum / issue system.

**Closed** 2018-11-03 18:11 UTC
Labels: wontfix
