### ISSUE TITLE
You are trying to sign in from a browser or app that doesn't allow us to keep your account secure.

### ISSUE THREAD

**Issue by eristoddle** [ramboxapp/community-edition#2495] opened 2019-11-27 02:07 UTC
### Steps to reproduce

1. Add Gmail or Google Hangouts to Rambox
2. Try to login

### Expected behavior

I can login.

### Actual behavior

Get this message:

You are trying to sign in from a browser or app that doesn't allow us to keep your account secure.
Try using a different browser. Learn more

### ENVIRONMENT

> Rambox: v0.7.2

> OS: Mac Mojave

> Arch: x64

I even tried changing the user agent to the user agent of my Chrome installation as suggested here: https://github.com/ramboxapp/community-edition/issues/2385 but that did not work

**Comment by fvulich** [comment] 2019-11-29 14:31
We want to know if you still have this problem, or we can close this ticket.

**Comment by eristoddle** [comment] 2019-11-29 17:25
Yeah, I still have this problem. Nothing I try seems to fix it. I did like using Rambox. Going to have to look for another tool I think though.

**Comment by babastienne** [comment] 2019-12-02 12:55
I get the same problem but on Linux OS. Same version of Rambox.

**Comment by darkeyce** [comment] 2019-12-02 22:26
Same issue. It also occurs in RamboxPro.
If you are already signed in on Rambox to a google APP, don't sign out. it will continue to work just fine. it's only NEW sign-in attempts that fail.

**Comment by fvulich** [comment] 2019-12-03 12:44
I couldn't reproduce the issue, could you tell us from which country are you trying to get logged? Could you try using a User Agent? We really want to fix this ASAP, but we need more information.

**Comment by saenzramiro** [comment] 2019-12-03 15:01
Guys, we cannot reproduce this problem. We think it is a new privacy policy Google is releasing in parts.

Any other idea you have will help us to reproduce the problem and fix it ASAP.

**Comment by darkeyce** [comment] 2019-12-03 16:05
I'm in the USA and it occurs consistently for me. 
I tried a chrome user agent for v.72 & 74 but it still occurs. if you have a suggestion for a different user agent I'll try that.

**Comment by babastienne** [comment] 2019-12-03 16:37
I'm in France. Still can't connect by default, but i tried with this user agent : `Mozilla/5.0 (platform; rv:geckoversion) Gecko/geckotrail Firefox/firefoxversion` and it worked, showing the old basic HTML version of gmail.
Wiih the user agent ` Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0 ` it worked perfectly, showing the last version of gmail.

**Comment by darkeyce** [comment] 2019-12-03 17:01
> I'm in France. Still can't connect by default, but i tried with this user agent : `Mozilla/5.0 (platform; rv:geckoversion) Gecko/geckotrail Firefox/firefoxversion` and it worked, showing the old basic HTML version of gmail.
> Wiih the user agent `Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0` it worked perfectly, showing the last version of gmail.

Neither of those Agents work for me from the US. :(

**Comment by franciscarriere** [comment] 2019-12-03 23:16
Same here. Was working fine yesterday and today it stopped working, same issue as others above. Changing the user agent does not affect it. I have 2FA

**Comment by fvulich** [comment] 2019-12-04 22:18
Some relevant links:

Electron Issue: Google Sign-in Breaking in June 2019 for embedded frameworks 
https://github.com/electron/electron/issues/17887

Chromium Group: Google to block sign-ins from Chromium embedders
https://groups.google.com/a/chromium.org/d/msg/embedder-dev/STyM5ZNTHMM/ir476rkhBAAJ

Google-Play-Music-Desktop-Player-UNOFFICIAL  Issue (the owner is in the Electron Project)
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3545

**Comment by darkeyce** [comment] 2019-12-05 06:52
@fvulich after reading through WAY to many git commits from the links you provided above, I found this user agent that works for me and allows me to log into Google services. While this works, the Pro development team needs to find the correct User Agent for and build it into the application.
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:58.0) Gecko/20100101 Firefox/58.0"
To make this work, you need to add this user agent in the settings of any Google service you want to use. From the hamburger menu, select tools and clear the cache. After these steps, I was able to log in to the services.

**Comment by daemoch** [comment] 2019-12-05 20:43
Mostly posting so I can follow.
I've been getting the login error for some time.  Just today I had a moment to reinstall and look at it again.  I'm not in a virtual environment, just a metal box I thrash regularly.
Adding Squirrel log here in case its useful.
[SquirrelSetup.log](https://github.com/ramboxapp/community-edition/files/3929043/SquirrelSetup.log)

**Comment by futurehaskins** [comment] 2019-12-05 23:06
Issue just started for me today, and boy am I unhappy about it. 

I've been poking around trying to figure out a user agent that works for me, but my Chrome install's user agent isn't it.

Version: 0.7.2
Platform: linux (x64) // Pop OS! 19.10, for clarity
Electron: 7.1.1
Chromium: 78.0.3904.99
Node: 12.8.1

**Comment by eristoddle** [comment] 2019-12-06 00:39
> @fvulich after reading through WAY to many git commits from the links you provided above, I found this user agent that works for me and allows me to log into Google services. While this works, the Pro development team needs to find the correct User Agent for and build it into the application.
> "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:58.0) Gecko/20100101 Firefox/58.0"
> To make this work, you need to add this user agent in the settings of any Google service you want to use. From the hamburger menu, select tools and clear the cache. After these steps, I was able to log in to the services.

This worked for me finally in the US.

**Comment by eristoddle** [comment] 2019-12-06 01:01
A note on that fix though. It created a similar error now with Slack

**Comment by fvulich** [comment] 2019-12-06 13:26
We're working on a built-in fix. It's gonna be part of a new release very soon.

**Closed** 2019-12-06 14:30 UTC
Labels: help wanted, investigate
