### ISSUE TITLE
[Threema] Received messages not marked as read

### ISSUE THREAD

**Issue by Kurisutian** [ramboxapp/community-edition#962] opened 2017-06-22 09:20 UTC
### Steps to reproduce

1. Start a Threema Chat
2. Receive a Threema Message
3. Switch to Rambox and answer message

### Expected behavior

When selecting the Threema Window (or at least when focusing into the text field to answer) Rambox should mark the received messages as read.

### Actual behavior

Most of the times the received messages remain marked as unread and you have to maximize the rambox window and resize it again afterwards to have these messages being marked as read.

### ENVIRONMENT

> Rambox: v0.5.9

> OS: Manjaro Linux

> Arch: x64

**Comment by saenzramiro** [comment] 2017-08-15 18:37
Is this still happening in latest version of Rambox?

**Comment by Kurisutian** [comment] 2017-08-15 18:46
Unfortunately yes, it also happens very often with version 0.5.10 as well.

**Comment by saenzramiro** [comment] 2017-10-10 15:00
Threema is marking the message as read but Rambox still showing the unread count? Is that the problem?

**Comment by Kurisutian** [comment] 2017-10-10 15:20
That's correct.

**Comment by saenzramiro** [comment] 2018-01-16 19:48
I couldn't reproduce this. Works for me.
@dbrgn Can you help us with this?

**Comment by dbrgn** [comment] 2018-01-16 21:32
Hm, it works for me too.

I actually have a different problem. In the browser, Threema Web will only mark messages as read if the conversation is open *and* the tab is open. In contrast, in Rambox, even when another tab/service is focussed, the messages are still marked as read in the background.

The focus detection is done using the page visibility API: https://github.com/threema-ch/threema-web/blob/364ccf448a74b07c0caaa343b6040ea23ca38adb/src/services/browser.ts#L31-L81 Maybe this is something where either Rambox can do something about it, or where we can add code to support Rambox?

**Closed** 2018-11-02 07:46 UTC
Labels: service-bug, wontfix

**Comment by dbrgn** [comment] 2018-11-02 07:47
This should be fixed with https://github.com/threema-ch/threema-web/pull/644.
