### ISSUE TITLE
Signup with Google account

### ISSUE THREAD

**Issue by Skybeat** [ramboxapp/community-edition#37] opened 2016-07-02 08:22 UTC
If i try to signuip and typ in my g-mail and my password and press de aignup button, i get a smal wintow with the title "Connecting...." and de message "Please wait until we get your configuration".
Then nothing more happens until i go to the Menu of Rambox "View -> Reload". 
After that i'm logged in with my google account.

**Comment by Jimi-James** [comment] 2016-07-03 03:06
Thanks for the tip. Mine got stuck, and I didn't know how to fix it until reading this and trying View -> Reload.

**Comment by saenzramiro** [comment] 2016-07-03 20:54
Thanks guys for this report. I will take a look for the next release.

**Comment by yafp** [comment] 2018-04-26 11:12
@Skybeat & @Jimi-James 
is that still a valid issue or is it fixed in the current 0.5.16 version?

**Comment by Jimi-James** [comment] 2018-04-26 16:59
Well, since it's an issue when you first sign up, and I've already done that, I couldn't really tell you. Is the reload workaround not working anymore?

**Comment by ozskywalker** [comment] 2018-05-04 02:28
Wasn't able to reproduce this on macOS 10.13.4 with rambox 0.5.17 / electron 1.8.6 ... would say it's been solved?

**Closed** 2018-11-02 04:46 UTC
Labels: bug, wontfix
