### ISSUE TITLE
Rambox don't save the file extension

### ISSUE THREAD

**Issue by oarad75** [ramboxapp/community-edition#1624] opened 2018-04-29 19:34 UTC
download a file from gmail and save it. The file will be save without the .ext so the OS is not able to handle it properly.

	
	-
	> Rambox 0.5.17
	> Electron 1.8.4
	> win32 x64 10.0.16299

**Comment by Ash258** [comment] 2018-04-29 21:28
Duplicate of #1009

**Comment by ozskywalker** [comment] 2018-05-04 02:13
Looks like an electron issue that's not resolved?  https://github.com/electron/electron/issues/9593

**Closed** 2018-11-01 02:20 UTC
Labels: wontfix
