### ISSUE TITLE
window size eventually conks out

### ISSUE THREAD

**Issue by ericzawo** [ramboxapp/community-edition#1092] opened 2017-08-24 14:31 UTC
After a month of using Rambox daily (and it's amazing!) The size of the Slack window is bigger than what's represented on my screen and can no longer access the text box at the bottom. Happened twice now and theonly solution I've found is to reinstall.

	
	-
	> Rambox 0.5.10
	> Electron 1.7.4
![screen shot 2017-08-24 at 10 30 50 am](https://user-images.githubusercontent.com/14874563/29671366-5cc1b3aa-88b7-11e7-9d79-e9937981686c.png)

![screen shot 2017-08-24 at 10 31 31 am](https://user-images.githubusercontent.com/14874563/29671380-6a72917c-88b7-11e7-9f6c-b66575207566.png)

	> darwin x64 16.5.0

**Comment by alexdevero** [comment] 2017-08-28 06:33
@ericzawo are you using a HiDPI monitor or notebook with HiDPI screen?

**Comment by ericzawo** [comment] 2017-08-28 12:52
^ Yes, I am on a 2015 13" retina macbook pro

**Comment by alexdevero** [comment] 2017-08-29 06:05
@ericzawo In that case, this issue may be related to #1088. I already made a fix https://github.com/saenzramiro/rambox/pull/1091 for this that is waiting for approval. I successfully tested the fix on Windows.

**Comment by edist** [comment] 2017-09-15 00:33
@alexdevero It looks like your change has been merged into the current version, but the problem is still persisting for me. Clearing the cache seemed to fix it the first time it happened, but it started again and now I can't get the windows to display correctly. I just installed Rambox today on a Windows 10 machine with a 3200 x 1800 screen.

**Comment by alexdevero** [comment] 2017-09-15 05:53
@edist Did you use the option for enabling scaling?

**Comment by edist** [comment] 2017-09-15 17:20
Well, now I feel stupid.

I enabled it and restarted properly and it fixes the issue but makes the Rambox interface tiny. I can deal with that, though. Thanks.

**Comment by ericzawo** [comment] 2017-10-08 16:06
Still broken on MacOS

**Closed** 2018-11-02 08:46 UTC
Labels: wontfix
