### ISSUE TITLE
I login using my twitter, back it up.. then it's on proccess and say ok. the rambox close and turn back on but it still sing out

### ISSUE THREAD

**Issue by donflaminggo** [ramboxapp/community-edition#2678] opened 2020-04-17 05:02 UTC
-
	> Rambox 0.7.5
	> Electron 7.1.12
	> win32 x64 10.0.18363

**Comment by carbeer** [comment] 2020-04-21 20:04
I am experiencing the same issue. I registered, and logged in and received an "OK" message in the pop up. However, after closing it, I am still not signed in and the configuration won't sync.

Version: 0.7.5
Platform: linux (x64)
Electron: 7.1.12
Chromium: 78.0.3904.130
Node: 12.8.1

**Comment by fvulich** [comment] 2020-04-22 15:34
After you sign in you need to verificate your email and then get logged. This link may help you out.
[Backup Rambox Services](https://github.com/ramboxapp/community-edition/wiki/Backup-Rambox-CE-services)

**Closed** 2020-04-22 15:34 UTC

**Comment by carbeer** [comment] 2020-04-22 15:37
Well yes. The issue is the login, both the OP and myself can't log in. 
After entering the login details it will return a plain 'OK' and that's it, while still not being signed in.

**Comment by fvulich** [comment] 2020-04-22 16:02
Great to hear that you could solve it! have a nice day.
