### ISSUE TITLE
Signal - Open Whisper Systems

### ISSUE THREAD

**Issue by draptik** [ramboxapp/community-edition#26] opened 2016-07-01 18:21 UTC
Is [Signal](https://whispersystems.org/) in the pipeline for future developments?

**Comment by saenzramiro** [comment] 2016-07-01 19:12
As I see, there isn't a Web App version for Signal. Am I wrong?

Of course, It will be great to add it.

**Comment by draptik** [comment] 2016-07-01 19:21
Not sure if a Google browser plugin counts as a web app:

https://chrome.google.com/webstore/detail/signal-private-messenger/bikioccmkafdpakkkcpdbppfkghcmihk?hl=en

**Comment by draptik** [comment] 2016-07-01 19:35
I have submitted a request with the Signal team to clarify if it's technically possible to include their service. I'll post back when I get an answer.

**Comment by saenzramiro** [comment] 2016-07-02 00:02
It's a web app but only for Google Chrome by an extention.

It will be great if they release a web app accesible by an URL, so we can add it to Rambox. Please, ping me here when you have news. For now, I will close this issue.

Thanks!

**Comment by draptik** [comment] 2016-07-07 09:56
Just a quick follow-up: The team from Signal is not planning to support  inter-app operability at the moment.

**Comment by saenzramiro** [comment] 2016-07-10 22:45
That's sad. 😞

**Comment by agharbeia** [comment] 2017-01-18 22:03
But is it technically feasible to refurbish Chromium's/Chrome's extension to work in the Rambox environment?

**Comment by ChromoX** [comment] 2017-01-25 20:37
I know Signal uses GCM(Google Cloud Messaging). I would expect that GCM is not included in Chromium.

**Comment by agharbeia** [comment] 2017-01-25 22:49
I have a vague idea about this. But I used Signal's web application in chromium and had set a stand-alone launcher for it in Ubuntu even. It seemed to me to operate normally.

**Comment by jensMF** [comment] 2017-02-09 14:24
The Chrome/Chromium extension uses websocket.

**Comment by onny** [comment] 2017-08-10 21:33
there are libraries you can use, see signal-cli here on github

**Comment by igalic** [comment] 2017-09-13 13:49
There's also a bunch of folks who've written about building signal with nwjs.io for instance: https://timtaubert.de/blog/2016/01/build-your-own-signal-desktop/

**Comment by Simon0Harms** [comment] 2017-11-01 09:10
This don't look like a normal "Web Interface" which rambox could implement.
This would be like implementing the better xmpp in rambox...

**Comment by jaredkotoff** [comment] 2017-11-01 16:28
It's not a web interface but it is electron

**Comment by jbbr** [comment] 2017-11-01 23:22
The new electron implementation of Signal does indeed make it possible to add Signal support in Rambox - at least in theory.

But:
Other Rambox services are basically only web pages shown in a frame + some JS for notification parsing. Adding Signal would require including/forking the code from https://github.com/WhisperSystems/Signal-Desktop

In the past WhisperSystems/moxie where not supportive of inofficial distributions of Signal clients if they use the use the official servers.
See the discussion regarding LibreSignal, a fork of Signal for Android: https://github.com/LibreSignal/LibreSignal/issues/37#issuecomment-217211165

So if anyone wants to implement this I would suggest to get in contact with WhisperSystems first to not get blocked from using their servers.

Maybe someone could try to get the code of Signal-Desktop running in a web browser (Without Electron) like WhatsApp Web (Which is by the way using the same encryption). If this would exist and be hosted somewhere it could be integrated into Rambox & co like every other service.

**Comment by rodneyrod** [comment] 2017-11-22 00:26
@jbbr Exactly this. I recommend closing all other issues and re-opening **THIS** issue and tag it something like 'Awaiting pull request' for someone to contribute the code and to make it clear that this issue won't be resolved until someone else contributes it.

**Comment by saenzramiro** [comment] 2017-12-14 14:11
Hello guys,

Like we know, now Electron supports adding extensions but I don't have time to play with it and add Signal Chrome App into Rambox.

Can anyone help with this?

**Comment by ruiumbelino** [comment] 2017-12-28 21:36
Any news on this?

**Comment by PuckStar** [comment] 2018-01-02 18:52
Also in interested in this!

**Comment by drderkummer** [comment] 2018-01-10 09:09
Im also interested. Any news?

**Comment by rodneyrod** [comment] 2018-03-18 22:07
@ruiumbelino The 'development team' is one guy who has stated several times he's not able to implement this himself. So unless you want to put in a pull request yourself, please don't fill up the comments.

**Comment by ruiumbelino** [comment] 2018-03-18 22:50
@rodneyrod,

What in your comment tell us about the current status of this possible new feature?

Is this project dead, or we just can't ask for some development updates, or new features?

**Comment by rodneyrod** [comment] 2018-03-18 23:10
@ruiumbelino Read the thread.
>Like we know, now Electron supports adding extensions but I don't have time to play with it and add Signal Chrome App into Rambox.
>Can anyone help with this?

That's the dev, he says that he doesn't have the time to put in this new feature and is asking for help.
The issue is here, and that's already a request for this new feature. Making new comments asking what the status is won't make the features come any faster.

**Comment by ruiumbelino** [comment] 2018-03-18 23:21
@rodneyrod,

Still nothing about what is being asked, but it seems you like to increase comments number...

Thanks a lot for your contribution.

**Comment by The-Loeki** [comment] 2018-10-25 13:12
I would still love this

**Comment by 5chdn** [comment] 2018-11-30 09:57
> It's a web app but only for Google Chrome by an extension.

The desktop version is no longer a chrome extension, I don't know if this was discussed here before. https://github.com/signalapp/Signal-Desktop

> It will be great if they release a web app accessible by an URL, so we can add it to Rambox. 

Is this a must-have requirement or a nice-to-have? I mean, would it be technically feasible to embed the standalone electron app that whispersystems provides?

> Like we know, now Electron supports adding extensions but I don't have time to play with it and add Signal Chrome App into Rambox.

Maybe we can crowdsource a bounty for this task. I just want to understand first, if this is A) desired, and B) feasible.

**Comment by ToggoStar** [comment] 2018-12-01 13:53
> 
> 
> > It's a web app but only for Google Chrome by an extension.
> 
> The desktop version is no longer a chrome extension, I don't know if this was discussed here before. https://github.com/signalapp/Signal-Desktop
> 
> > It will be great if they release a web app accessible by an URL, so we can add it to Rambox.
> 
> Is this a must-have requirement or a nice-to-have? I mean, would it be technically feasible to embed the standalone electron app that whispersystems provides?
> 
> > Like we know, now Electron supports adding extensions but I don't have time to play with it and add Signal Chrome App into Rambox.
> 
> Maybe we can crowdsource a bounty for this task. I just want to understand first, if this is A) desired, and B) feasible.
> 
> Edit: relevant tickets are [signalapp/Signal-Desktop#723](https://github.com/signalapp/Signal-Desktop/issues/723) and [signalapp/Signal-Desktop#542](https://github.com/signalapp/Signal-Desktop/issues/542) - doesn't look good. Maybe we just have to start using wire which is much more open, private, and supported by rambox!

For me, it would be a must-have and I would be willing to contribute to a bounty!

**Comment by The-Loeki** [comment] 2019-01-30 18:48
I still care

**Comment by 5chdn** [comment] 2019-01-30 23:36
Let's make this happen!

**Closed** 2019-02-07 06:44 UTC
Labels: new service, wontfix

**Comment by 5chdn** [comment] 2019-02-07 11:22
![99166386_france_trans_nvbqzqnjv4bqqvzuuqpflyliwib6ntmjwfsm8sv5nixqond2k-jcc_u](https://user-images.githubusercontent.com/15729797/52408367-1036be80-2ad3-11e9-80e3-9b836b3f67aa.jpg)
