### ISSUE TITLE
Slack calls not working within Rambox

### ISSUE THREAD

**Issue by jacobomarquis** [ramboxapp/community-edition#2366] opened 2019-08-07 10:55 UTC
### Steps to reproduce

1. Open Slack call in any channel or private message

### Expected behavior

Call handled within Rambox as it used to be

### Actual behavior

The first call you make will open a new default browser window will open the first time, requiring to authenticate. The next time you try to make a call the browser window will not open anything

### ENVIRONMENT

> Rambox: v0.6.9

> OS: Ubuntu 18.04

> Arch: x64

**Comment by svenjacobs** [comment] 2019-09-05 05:58
Having the same problem. Rambox version 0.6.9 on macOS 10.14.6.

**Comment by StormPooper** [comment] 2019-09-24 12:56
Same problem.

```
Version: 0.6.9
Platform: win32 (x64)
Electron: 4.1.4
Chromium: 69.0.3497.128
Node: 10.11.0
```

**Comment by timrettop** [comment] 2019-10-09 21:37
Also experiencing this, any feedback? 

Version: 0.6.9
Platform: darwin (x64)
Electron: 4.1.4
Chromium: 69.0.3497.128
Node: 10.11.0

**Comment by dmtask** [comment] 2019-12-10 14:54
Same Problem:

Version: 0.7.2
Plattform: darwin (x64)
Electron: 7.1.1
Chromium: 78.0.3904.99
Node: 12.8.1

**Comment by alien2003** [comment] 2020-02-19 08:49
The same here:
	-
	> Rambox 0.7.3
	> Electron 7.1.1
	> linux x64 5.4.18-1-MANJARO

**Comment by vinsgithub** [comment] 2020-03-04 10:46
same here
Version: 0.7.3
Platform: linux (x64)
Electron: 7.1.1
Chromium: 78.0.3904.99
Node: 12.8.1

**Comment by svenjacobs** [comment] 2020-03-24 06:45
@fvulich It would be nice to know what additional information you need instead of just adding a label 😉 Are the reported information not enough?

**Comment by svenjacobs** [comment] 2020-03-24 10:52
As described by OP, the first call opens a browser window. After the browser window is closed, this is the error that I see in the console of Rambox. Further clicks on the call button cause the same error.

```
gantry-vendors.1f26a77.min.js?cacheKey=gantry-1585009991:1 TypeError: Cannot read property 'closed' of null
    at remote_window_RemoteWindow.isClosed (gantry-shared.7502724.min.js?cacheKey=gantry-1585009991:1)
    at client-boot-imports.8db5edb.min.js?cacheKey=gantry-1585009991:1
    at n (gantry-vendors.1f26a77.min.js?cacheKey=gantry-1585009991:1)
    at G3A0.t.a (gantry-vendors.1f26a77.min.js?cacheKey=gantry-1585009991:1)
    at HI9p.t.a (gantry-vendors.1f26a77.min.js?cacheKey=gantry-1585009991:1)
    at gantry-vendors.1f26a77.min.js?cacheKey=gantry-1585009991:1
    at client-boot-imports.8db5edb.min.js?cacheKey=gantry-1585009991:1
    at client-boot-imports.8db5edb.min.js?cacheKey=gantry-1585009991:1
    at gantry-vendors.1f26a77.min.js?cacheKey=gantry-1585009991:1
    at gantry-vendors.1f26a77.min.js?cacheKey=gantry-1585009991:1
    at G5n0.t.a (gantry-vendors.1f26a77.min.js?cacheKey=gantry-1585009991:1)
    at gantry-vendors.1f26a77.min.js?cacheKey=gantry-1585009991:1
    at Ws7a.t.a (gantry-vendors.1f26a77.min.js?cacheKey=gantry-1585009991:1)
    at t.a (gantry-vendors.1f26a77.min.js?cacheKey=gantry-1585009991:1)
    at P (client-boot-imports.8db5edb.min.js?cacheKey=gantry-1585009991:1)
    at Function.mapToProps (client-boot-imports.8db5edb.min.js?cacheKey=gantry-1585009991:1)
```

**Comment by fvulich** [comment] 2020-03-24 13:03
We are investigating this issue, we couldn't find the culprit yet. And I added the label to encourage users to post all the information that seems relevant to them, hoping that someone get us a lead.

**Comment by parcae** [comment] 2020-03-24 15:00
> We are investigating this issue, we couldn't find the culprit yet. And I added the label to encourage users to post all the information that seems relevant to them, hoping that someone get us a lead.

It should be easy to reproduce. I experienced the same behavior today with my trial version of RamboxPro. What information do you need to investigate it. Do I need to gather specific info? If so, let me know and I will reproduce it again.

Since I am on the trial version, I would love the videocall settings to be working before buying a license.

**Comment by fvulich** [comment] 2021-08-10 13:25
0.7.9 Released (this issue is fixed in it). You can download it from [HERE](https://github.com/ramboxapp/community-edition/releases/latest)

**Closed by fvulich** 2021-08-10 13:25 UTC
Labels: investigate, help wanted, more-information-needed
