### ISSUE TITLE
Slack not supporting Rambox browser in future

### ISSUE THREAD

**Issue by brinesharks** [ramboxapp/community-edition#3040] opened 2021-06-28 09:13 UTC
Slack is showing a warning message that it will no longer support the Rambox browser after July this year. It advises to change browsers or use Slack app. I'd prefer to keep using Rambox,

	
	-
	> Rambox 0.7.7
	> Electron 7.2.4
	> win32 x64 10.0.19042

**Comment by jblion** [comment] 2021-06-28 10:32
Duplicate of #3036 ?

**Closed** 2021-06-28 12:37 UTC
Labels: duplicate
