### ISSUE TITLE
"Search with Google" context menu link not working. Wrong link

### ISSUE THREAD

**Issue by jimmylad** [ramboxapp/community-edition#2969] opened 2021-02-18 07:11 UTC
### Steps to reproduce

1. Select text
2. Right click -> Search with Google
3. No results shown in Google page. URL not working.

### Expected behavior

URL directed to should be https://www.google.com/search?q=test

### Actual behavior

URL directed is currently https://www.google.com/#q=test

### ENVIRONMENT

> Rambox: v0.7.7

> OS: Mac OSX 10.13.6

> Arch: x64

> Chrome 88.0.4324.150

**Comment by fvulich** [comment] 2021-02-26 18:18
We couldn't reproduce this issue, it works as it should. With the correct URL. 
Could you try doing a Clear cache & a Clear Storage and tell us how it goes? Before doing this, backup all your services following [this tutorial](https://github.com/ramboxapp/community-edition/wiki/Backup-Rambox-CE-services) , because you will lose them.
![image](https://user-images.githubusercontent.com/46904390/80006611-8090ec00-849b-11ea-9af6-cd8c75d01d2e.png)


If that doesn't work either, please, try uninstalling/reinstalling Rambox CE, [this guide (Clean uninstall)](https://github.com/ramboxapp/community-edition/wiki/Clean-Uninstall) will help you out.

**Comment by jimmylad** [comment] 2021-03-01 09:41
Thanks. I tried all of those steps and the issue remains, clicking " Search with Google" takes me to https://www.google.com/#q=[highlighted_text]

**Comment by alphard177** [comment] 2021-03-13 06:12
I get the same thing with tweetdeck.

**Comment by qz2501** [comment] 2021-03-13 11:33
My Rambox has the exactly same issue. 


Version: 0.7.7
Platform: win32 (x64)
Electron: 7.2.4
Chromium: 78.0.3904.130
Node: 12.8.1

**Comment by Piroro-hs** [comment] 2021-03-15 01:35
Same issue

Version: 0.7.7
Platform: win32 (x64)
Electron: 7.2.4
Chromium: 78.0.3904.130
Node: 12.8.1

**Comment by flubb** [comment] 2021-03-15 09:17
Same issue here

Version: 0.7.7
Plateforme: win32 (x64)
Electron: 7.2.4
Chromium: 78.0.3904.130
Node: 12.8.1

**Comment by nheinemans** [comment] 2021-03-29 05:57
Same issue here (same versions as previous 3 comments)

**Comment by fvulich** [comment] 2021-08-02 13:33
0.7.8 Released (this issue is fixed in it). You can download it from [HERE](https://github.com/ramboxapp/community-edition/releases/latest)

**Closed by fvulich** 2021-08-02 13:33 UTC
Labels: bug
