### ISSUE TITLE
Google services are signed out once a week

### ISSUE THREAD

**Issue by sleepyspider1** [ramboxapp/community-edition#2444] opened 2019-11-18 18:06 UTC
About once a week, I'm signed out of all google services and have to log into each tab again individually. I'm not sure if this is a google thing or a rambox thing.

**Comment by fvulich** [comment] 2019-11-29 14:27
It seems to be an isolated case, no one else reported it, and we couldn't reproduce it. I will close this ticket but if the issue continues please come back.

**Closed by fvulich** 2019-11-29 14:27 UTC

**Comment by boekkooi-fresh** [comment] 2019-11-29 14:42
I can confirm that this happens every week on both gmail and calendar
