### ISSUE TITLE
cannot Open link on New Skype

### ISSUE THREAD

**Issue by medeka77** [ramboxapp/community-edition#2121] opened 2019-03-11 06:09 UTC
When my friends send link i cannot open it, i must copy the link and manualy paste on browser. Also i must disable link preview. This issue not occurs in previous skype, can using right click mouse and then open. there are no option to open link

Step:
1. Click Link
2. nothing happen

	
	-
	> Rambox 0.6.3
	> Electron 2.0.14
	> win32 x64 10.0.17134

**Comment by Digioso** [comment] 2019-03-11 19:23
I have the same issue.

**Comment by nzeppos** [comment] 2019-03-12 08:24
This is a duplicate of https://github.com/ramboxapp/community-edition/issues/2116, we have already proposed a workaround there.

**Comment by saenzramiro** [comment] 2019-03-15 06:49
Duplicate #2116.

**Closed by saenzramiro** 2019-03-15 06:49 UTC
