### ISSUE TITLE
Microsoft Teams "Unread counter" function is not working.

### ISSUE THREAD

**Issue by jiayuan** [ramboxapp/community-edition#2066] opened 2019-01-17 03:20 UTC
###Steps:

1. Open Microsoft Teams Options
2. Under Unread counter section, check "Display tab unread counter" and "Include in global unread counter"
3. Click on Edit
4. Tested messaging.
5. Rambox does not display unread counter on Mac OS Dock icon.

![image](https://user-images.githubusercontent.com/1509664/51293394-b6018b00-1a49-11e9-9417-14f76b874699.png)

	
	-
	> Rambox 0.6.3
	> Electron 2.0.14
	> darwin x64 18.2.0

**Comment by dguyonvarch** [comment] 2019-01-17 16:38
Is this a duplicate of #2020 ?

**Comment by jiayuan** [comment] 2019-01-18 09:31
> Is this a duplicate of #2020 ?

yes

**Comment by jiayuan** [comment] 2019-01-18 09:32
apologies, clicked on "closed" status by mistake.

**Comment by fvulich** [comment] 2019-02-01 19:06
#2008 take a look at this issue, it may help you.

**Comment by jiayuan** [comment] 2019-02-02 02:12
Thank you! Will give it a try and update if it works

**Comment by jiayuan** [comment] 2019-02-04 02:57
> #2008 take a look at this issue, it may help you.

This works, thank you!

**Closed** 2019-02-11 15:41 UTC
