### ISSUE TITLE
A JavaScript error occured in the main process

### ISSUE THREAD

**Issue by emmanuelvinet** [ramboxapp/community-edition#1848] opened 2018-09-04 12:50 UTC
A JavaScript error occured in the main process each time I'm browsing Rambox tabs.

	
	-
	> Rambox 0.5.17
	> Electron 1.8.4
	> win32 x64 10.0.16299

**Comment by Ash258** [comment] 2018-09-04 12:53
Could you provide screenshot or stacktrace or anything, that could help?

**Comment by emmanuelvinet** [comment] 2018-09-04 13:12
Here you are, thanks.

![capture_rambox_javascript_error](https://user-images.githubusercontent.com/42810517/45033442-d578b800-b054-11e8-9176-af66a4148be5.PNG)

**Comment by Ash258** [comment] 2018-09-04 13:20
Duplicate of #1656

**Closed by Ash258** 2018-09-04 13:20 UTC
