### ISSUE TITLE
[rfe] Add messages.android.com

### ISSUE THREAD

**Issue by e-minguez** [ramboxapp/community-edition#1825] opened 2018-08-22 08:30 UTC
Manually using the following works fine, but it would be nice to have it by default:

- Logo: https://www.phonedog.com/sites/phonedog.com/files/styles/blog_entry/public/androidmessageslarge.jpg
- URL: https://messages.android.com/

**Comment by Ash258** [comment] 2018-08-22 08:58
Duplicate of #1723

**Closed by Ash258** 2018-08-22 08:58 UTC
