### ISSUE TITLE
Custome Services show white screen, then rambox crashes when refresh the service

### ISSUE THREAD

**Issue by miguelhp89** [ramboxapp/community-edition#3063] opened 2021-08-03 07:36 UTC
### Steps to reproduce

1. Create a custome service to access facebook
2. Custome service added succesfully
3. Then custome service show a white screen, when try to  refresh the service rambox crashes. This happens since the last update 02/08/2021 (0.7.8)

### Expected behavior

Rambox should show Facebook app /Instagram app after refreshing the custome service created, not a white screen and not even crash. This was working ok in previous versions of rambox.

### Actual behavior

application crash
![Captura de pantalla de 2021-08-03 09-34-47](https://user-images.githubusercontent.com/64214167/127976399-83d44680-75e8-4eda-b7dd-27e3a4467252.png)
![Captura de pantalla de 2021-08-03 09-35-04](https://user-images.githubusercontent.com/64214167/127976423-7e82905c-6e35-4616-9ecc-f8ca5003a774.png)

### ENVIRONMENT

> Rambox: v0.7.8

> OS: Ubuntu 18.04

> Arch: x64

**Comment by extall** [comment] 2021-08-03 09:15
I confirm that this issue exists also in Windows 10 and started occurring after the update to Rambox v.0.7.8.

### ENVIRONMENT

> Rambox: v0.7.8

> OS: Win 10

> Arch: x64

**Comment by Xendar-IT** [comment] 2021-08-03 10:00
Same problem here, Windows 10 x64, after the update all custom services are not working (white page), and if you right click the tab and refresh the page, Rambox 0.7.8 crashes, but Rambox processes remain still active using 100% on all CPUs.

**Comment by Rejected-Peice** [comment] 2021-08-03 10:07
Same issue with Irccloud (https://uploads.kiwiirc.com/files/cd908d728e0b97a6a72aeea0e5540ad2/image.png)

ENVIRONMENT
Rambox: v0.7.8
OS: Win 10 Pro
Arch: x64

**Comment by ssbarnea** [comment] 2021-08-03 14:33
Same happens for me with google meet server but not with the others, just after the upgrade. MacOS x64

**Comment by Rejected-Peice** [comment] 2021-08-03 14:42
Sorry, I forgot to mention it.
I faced the issue after I upgraded.
Now I downgraded. But auto-updater is ready to install new version. I am not gonna reload rambox 😅

**Comment by miguelhp89** [comment] 2021-08-03 14:59
> Sorry, I forgot to mention it.
> I faced the issue after I upgraded.
> Now I downgraded. But auto-updater is ready to install new version. I am not gonna reload rambox sweat_smile

Yeah, I'm doing the same until the solution arrives

**Comment by ssbarnea** [comment] 2021-08-03 16:22
The irony is that containing/isolating meet from the normal browse was by far the no1 reason why I started to use rambox few months back, using a conferencing app as a browser tab is a nightmare. I often end up not being able to find the conference tab between my other ones.

Apparently Google is on a spree to kill anyone that not using Chrome.

**Comment by schousda** [comment] 2021-08-03 18:18
Same here.
After the update my custom services only show a blank page. I have some of the for different twitter accounts.

**Comment by extall** [comment] 2021-08-03 19:35
Looks like a problem with either Electron, or a regression bug.

**Comment by monkeylove** [comment] 2021-08-04 10:30
I wonder if it's possible to disable auto-updating, so that we can stick to version 0.7.7 until the problem is fixed.

**Comment by extall** [comment] 2021-08-04 10:56
@monkeylove : you can start Rambox with a command line switch. On Windows, I have this in the target field of the shortcut:
```"C:\Program Files\Rambox\Rambox.exe" --without-update```
You should also disable autostart in Rambox, and if you still want it to autostart, you need to copy that shortcut to the `startup` folder (again referring to Windows).

**Comment by miguelhp89** [comment] 2021-08-04 11:00
> @monkeylove : you can start Rambox with a command line switch. On Windows, I have this in the target field of the shortcut:
> `"C:\Program Files\Rambox\Rambox.exe" --without-update`
> You should also disable autostart in Rambox, and if you still want it to autostart, you need to copy that shortcut to the `startup` folder (again referring to Windows).

it is possible also with snap or deb package in ubuntu?

**Comment by extall** [comment] 2021-08-04 11:05
@miguelhp89 : there is an old issue: #1521 
Looks like it has not been resolved yet.

**Comment by fvulich** [comment] 2021-08-06 18:12
We are working in a better fix but for the moment you can add `--disable-features=CrossOriginOpenerPolicy` to the shortcut

**Comment by saenzramiro** [comment] 2021-08-06 20:16
This is related with an Electron bug: https://github.com/electron/electron/issues/25469

**Comment by bjpier** [comment] 2021-08-07 05:46
Having same issue with custom Facebook..  just white screen.. it does show when I get a new notification in facebook but everything is all white.

**Comment by saenzramiro** [comment] 2021-08-09 18:14
This is fixed in v0.7.9, thank you all for your patience!

**Closed by saenzramiro** 2021-08-09 18:14 UTC
Labels: bug, electron-bug-assumption
