### ISSUE TITLE
WE'RE SORRY, SOMETHING WENT WRONG WHEN ATTEMPTING TO LOG IN.

### ISSUE THREAD

**Issue by pdp-7** [ramboxapp/community-edition#1843] opened 2018-09-01 21:33 UTC
Singed in. All seems to be ok. When tried to log in it says "WE'RE SORRY, SOMETHING WENT WRONG WHEN ATTEMPTING TO LOG IN."

Hit the "Don't remember your password?" and changed it successfully, but alas, it's the same thing again.

What to do?

Thanks!

	
	-
	> Rambox 0.5.17
	> Electron 1.8.4
	> linux x64 4.13.0-46-generic

**Comment by Ash258** [comment] 2018-09-01 21:40
Duplicate of #1698

**Closed by Ash258** 2018-09-01 21:40 UTC
