### ISSUE TITLE
Keyboard shortcuts to cycle through service tabs doesn't work

### ISSUE THREAD

**Issue by fanis** [ramboxapp/community-edition#2125] opened 2019-03-15 08:35 UTC
### Steps to reproduce

1. Update to 0.6.4
2. Have multiple service tabs running (I have Whatsapp, Skype, Mattermost, Messenger)
3. Focus in one of them while using it.
4. Hit CTRL+TAB or CTRL+PGUP/PGDN to cycle through them

### Expected behavior

Tab switches to the next one on the right like it did in previous versions.

### Actual behavior

Nothing happens.
If you mouse click on the Service tab header itself (eg the "Whatsapp" icon and text) and then hit CTRL+TAB or CTRL+PGUP it works just once. You then need to mouse click on the current Service tab header again before CRTL+TAB or CTRL+PGUP to switch to the next one.

Looks like this functionality was introduced in #75. I've been using it for many versions.

### ENVIRONMENT

Rambox 0.6.4
Electron 3.1.4
win32 x64 10.0.17134

**Comment by sylvainar** [comment] 2019-03-15 08:42
Same here !
Version: 0.6.4
Plateforme: win32 (x64)
Electron: 3.1.4
Chromium: 66.0.3359.181
Node: 10.2.0
Windows 10

**Comment by StormPooper** [comment] 2019-03-15 08:51
Same:
**Version:** 0.6.4
**Platform:** win32 (x64)
**Electron:** 3.1.4
**Chromium:** 66.0.3359.181
**Node:** 10.2.0

**Comment by maxerbox** [comment] 2019-03-15 11:21
Can confirm

**Comment by rwkyyy** [comment] 2019-03-15 11:52
Not working on macOS either.

**Comment by BalintFarkas** [comment] 2019-03-15 11:58
Can confirm on Windows 10
Version: 0.6.4
Platform: win32 (x64)
Electron: 3.1.4
Chromium: 66.0.3359.181
Node: 10.2.0

**Comment by LionelBino** [comment] 2019-03-15 12:46
Same here
ubuntu 18.04

**Comment by crimsonsunset** [comment] 2019-03-15 15:57
might revert until this is fixed. i slam that shortcut all day =/

**Comment by joaopsys** [comment] 2019-03-15 18:31
Same here:

Version: 0.6.4
Platform: linux (x64)
Electron: 3.1.4
Chromium: 66.0.3359.181
Node: 10.2.0

**Comment by maxerbox** [comment] 2019-03-15 19:16
Since chromium's architecture has been reworked, events are not propaged globally anymore. Rambox was using this hack to handle CTRL+TAB, but with the new electron version, it's not working anymore.
A workaround is to handle the events fired by webview.
Fixed in #2138

**Comment by RicoLaaa** [comment] 2019-03-18 08:51
+1 really a pain when you are using multiple services... which is the main purpose of Rambox.. :/

**Comment by SebastianMueller87** [comment] 2019-03-19 12:00
+ 1 (MacOs)

**Comment by maxerbox** [comment] 2019-03-19 21:29
I neee some reviewers for the push request ^^, feel free to review it

**Comment by lasombra** [comment] 2019-03-20 06:59
I tried to test the PR but I can't get Rambox to run properly.

sencha app watch fails with this message:
```
[ERR] /home/iweiss/.local/bin/Sencha/Cmd/6.7.0.63/plugin.xml:378: The following error occurred while executing this line:
/home/iweiss/Development/Personal/rambox-ce/.sencha/app/build-impl.xml:252: The following error occurred while executing this line:
/home/iweiss/Development/Personal/rambox-ce/.sencha/app/watch-impl.xml:87: The following error occurred while executing this line:
/home/iweiss/Development/Personal/rambox-ce/.sencha/app/build-impl.xml:291: The following error occurred while executing this line:
/home/iweiss/Development/Personal/rambox-ce/.sencha/app/sass-impl.xml:205: The following error occurred while executing this line:
/home/iweiss/Development/Personal/rambox-ce/.sencha/app/sass-impl.xml:297: Problem: failed to create task or type x-compass-compile
Cause: The name is undefined.
Action: Check the spelling.
Action: Check that any custom tasks/types have been declared.
Action: Check that any <presetdef>/<macrodef> declarations have taken place.

[ERR] A log is available in the file "/home/iweiss/Development/Personal/rambox-ce/sencha-error-20190320-2.log"
```

**Comment by lasombra** [comment] 2019-03-20 07:09
I tested the PR. Ctrl+number works fine. Ctrl+PgUp or Ctrl+PgDown doesn't work reliably.

**Comment by BalintFarkas** [comment] 2019-03-20 10:48
@maxerbox I tried to build Rambox from source to but failed with some cryptic Sencha error that I was unable to fix. If you can please provide a win64 build I'll test it gladly.

**Comment by crimsonsunset** [comment] 2019-03-20 18:38
> I tested the PR. Ctrl+number works fine. Ctrl+PgUp or Ctrl+PgDown doesn't work reliably; it seems it gets captured by the webview.

any idea if it fixes ctrl+tab / ctrl+shift+tab ?

**Comment by lasombra** [comment] 2019-03-21 06:30
Ctrl+Tab / Ctrl+Shift+Tab works, but I just noticed that all working shortcuts only work after you click on a tab, any tab. Then the shortcuts work.

It looks like the keyboard focus is on the webview when you start Rambox. Only after clicking on a tab that the shortcuts start to work normally.

**Comment by metal3d** [comment] 2019-03-21 09:38
@lasombra it doesn't work as expected, It only switch one tab, and then... nothing happens

**Comment by metal3d** [comment] 2019-03-21 09:41
Note: If your on the Rambox welcom tab, CTRL+PageDown works if you clicked on the tab title. Then, after the first switch, nothing happens on that shortcut. It seems that the webview is capturing the keyboard.

**Comment by maxerbox** [comment] 2019-03-21 17:37
@metal3d @lasombra 
Fixed pageup-pagedown-zoomin-zoomout issue

**Comment by lasombra** [comment] 2019-03-22 06:30
@maxerbox Good stuff! To me, the remaining problem is the initial usage of the shortcut requiring a click on any tab to work.

**Comment by maxerbox** [comment] 2019-03-22 06:46
Wdym ? You need to focus rambox window to make it working anyway.
It seems working even from the Rambox tab (where you add services)

**Comment by lasombra** [comment] 2019-03-22 07:12
Ah, never mind @maxerbox, sorry for the confusion. The problem is that the dev tools, which open side by side to the webview, has the initial focus.

**Comment by metal3d** [comment] 2019-03-27 15:27
@maxerbox I'm impatient to use the next release so :)

**Closed** 2019-03-27 20:24 UTC
Labels: bug
