### ISSUE TITLE
WhatsApp-Tab shows one unread message, but I have no new messages

### ISSUE THREAD

**Issue by ZipitoOverkill** [ramboxapp/community-edition#2906] opened 2020-11-24 08:06 UTC
WhatsApp-Tab shows one unread message, but there is none (I have no new messages)
Things I've tried: reloading the tab, removing the tab
![2020-11-24 09_04_52-Window](https://user-images.githubusercontent.com/51945084/100065582-3ce8d100-2e34-11eb-856e-26abde10466c.png)
.

	
	-
	> Rambox 0.7.7
	> Electron 7.2.4
	> win32 x64 10.0.19042

**Comment by Lefky** [comment] 2020-11-24 08:26
Duplicate of #2903

**Closed** 2020-11-24 15:42 UTC
