### ISSUE TITLE
Statusbar can't be closed

### ISSUE THREAD

**Issue by Rinma** [ramboxapp/community-edition#1112] opened 2017-08-30 16:22 UTC
The statusbar can't be closed because the tooltip appears to fast and too big.

![bildschirmfoto von 2017-08-30 18-19-35](https://user-images.githubusercontent.com/1405824/29883239-f74b88f4-8daf-11e7-9687-c1e7ac0ab6c3.png)

To reproduce start rambox and add a service and try to close the statusbar

	
	-
	> Rambox 0.5.10
	> Electron 1.7.4
	> linux x64 4.12.8-2-ARCH

**Comment by nmat** [comment] 2017-08-30 17:54
duplicate of: https://github.com/saenzramiro/rambox/issues/1014

**Closed** 2018-11-02 08:46 UTC
Labels: wontfix
