### ISSUE TITLE
Unable to Start Minimized

### ISSUE THREAD

**Issue by madjoe** [ramboxapp/community-edition#1318] opened 2017-11-23 04:11 UTC
### Steps to reproduce

1. Turn OFF your PC
2. Turn ON your PC
3. See the Rambox window pops up.

### Expected behavior
Since I already checked the following settings:
+ Start automatically on system startup
+ Start minimized
+ Auto hide menu bar (Alt key to display)

... I would expect NO Rambox Window to show up on system startup, or when you close the app and open it again.

### Actual behavior

The Rambox window shows up!

### ENVIRONMENT

> Rambox: v0.5.13-108

> OS: elementary OS 0.4.1 Loki

> Arch: x64

**Comment by g0r3** [comment] 2017-12-02 11:04
I can confirm this.

ENVIRONMENT

Rambox: v0.5.13
OS: Ubuntu 17.10 Budgie
Arch: x64

**Comment by gerardo-junior** [comment] 2017-12-03 08:01
Same problem over here, but sometimes it does not open, who opens is the electron build.

> Rambox: v0.5.13-2
> OS: ArchLinux rolling release
> Arch: x64

**Comment by Crouze** [comment] 2017-12-05 18:36
Same here, regardless of settings Rambox (auto) starts but not minimized.

Rambox v0.5.13
OS: Arch Linux x64 (up to date)
DE: Cinnamon 3.6.6

I have  a workaround, in which Rambox is started by a bash script, after which xdotool minimizes it.

**Comment by orschiro** [comment] 2018-02-17 09:38
Duplicate of https://github.com/saenzramiro/rambox/issues/1205?

**Closed** 2018-11-02 11:46 UTC
Labels: wontfix
