### ISSUE TITLE
Rambox requires High performance GPU 

### ISSUE THREAD

**Issue by IceHismxx** [ramboxapp/community-edition#538] opened 2016-12-24 02:45 UTC
### Steps to reproduce

1.  Run Rambox on OSX and look at activity monitor to see that the dedicated GPU in use.

### Expected behavior

Computer should not switch to dedicated GPU which saps a lot of battery for just a all-in-one messaging app.

### Actual behavior

Process switches dedicated GPU on
You can see it in this image here
https://imgroll.net/i/hqJEV

### ENVIRONMENT
The only services I am using right now is WhatsApp, Messenger, Irccloud, and Tweetdeck.

> Rambox: v0.4.5

> OS: MacOS

> Arch: x64

**Comment by saenzramiro** [comment] 2016-12-27 14:42
Try to disable the hardware acceleration in the Preferences.

**Comment by joaomlneto** [comment] 2017-01-26 14:34
Using the gfxCardStatus utility, it's the process "Rambox Helper" that forces the OS to use the discrete graphics.

I can confirm disabling the hardware acceleration in preferences solves the discrete graphics-switching problem.

macOS 10.12.2, Rambox 0.5.2

**Comment by saenzramiro** [comment] 2017-01-26 18:19
Thanks!

**Comment by Aktariel** [comment] 2017-02-23 08:36
I'm curious as to why this was closed; disabling hardware acceleration shouldn't even be necessary except for troubleshooting (IMHO), let alone be considered a "fix." 

It's entirely possible to create OpenGL contexts that don't require the dedicated GPU at all, and an application can tell macOS to explicitly *NOT* use the dedicated GPU.

Some good information about this [HERE.](http://mjtsai.com/blog/2016/12/13/the-discrete-gpu-and-you/)

**Comment by cbenhagen** [comment] 2017-08-13 15:26
@saenzramiro please reopen

**Comment by joaomlneto** [comment] 2017-08-13 15:31
My temporary fix for this is to manually ```sudo pkill -9 "Rambox Helper"``` after starting RamBox.
I don't really know if this causes any instability in the application, but works good enough for me.

**Comment by saenzramiro** [comment] 2017-10-10 14:20
Seems to be a Chromium/Electron bug. Please see here: https://github.com/electron/electron/issues/4380

Try to add `--disable-gpu` like [THIS](https://github.com/electron/electron/issues/4380#issuecomment-191832725) comment indicates.

**Comment by ideologysec** [comment] 2017-12-02 01:22
would love to see this added into Rambox; from my experience it is Slack alone that is causing the issues -- it's when a Slack channel is loaded that the discrete GPU kicks in. Any possibility of adding that flag to Rambox? Or if there's a way to add it as part of the custom javascript - but not that I could find.

**Comment by newzealandpaul** [comment] 2018-07-15 08:54
Would be great to have the "--disable-gpu" option in the RamBox preferences. I too can't run the discrete GPU when on battery.

**Closed** 2018-11-02 05:46 UTC
Labels: wontfix
