### ISSUE TITLE
Usability Improvement

### ISSUE THREAD

**Issue by CoalaJoe** [ramboxapp/community-edition#1529] opened 2018-03-12 19:23 UTC
### Steps to reproduce

1. Open a messager inside rambox
2. Press Ctrl+W or Cmd+W

### Expected behavior

Close that messenger

### Actual behavior

Closes rambox

### ENVIRONMENT

> Rambox: v0.5.16

> OS: High Sierra

> Arch: x64

**Comment by Lazza** [comment] 2018-03-14 14:42
This is not specific to macOS though.

**Comment by CoalaJoe** [comment] 2018-03-14 17:14
@Lazza Thanks. Updated issue.

**Comment by Ash258** [comment] 2018-03-14 21:36
@CoalaJoe How should **Close that messenger** should looks like? What should rambox do? LIke move to another service or what?

**Comment by CoalaJoe** [comment] 2018-03-15 09:10
@Ash258 Disable would be okay.

**Comment by 88scythe** [comment] 2018-03-15 15:37
I'm not sure if this is really the intended behaviour of Rambox, disabling or "closing" services on the spot seems to go against the whole intent of Rambox.

**Comment by marczz** [comment] 2018-03-18 14:27
It depends what kind of user you are, may be you want never miss a message or a notification, and all your services are always needed. Personally there are some of services I seldom use, and many I just check once a day. I don't want to keep 150M of resident memory for these inactive services, so I disable/re-enable them in the service tab. A keyboard shortcut is not necessary, but using Ctrl-W to disable the service as propose @CoalaJoe  would be coherent with the web browser behavior where Ctrl-W close the tab in focus, while Ctrl-Q close the application. Ctrl-W to close rambox is an odd behavior.

**Closed** 2018-10-31 23:36 UTC
Labels: wontfix
