### ISSUE TITLE
Error resizing Rambox Window

### ISSUE THREAD

**Issue by User991** [ramboxapp/community-edition#2553] opened 2020-01-14 12:11 UTC
Each time i try to resize the Rambox window i see this error:
![image](https://user-images.githubusercontent.com/17948689/72343503-51feba80-36cf-11ea-9b4e-30a16ec040f2.png)

	
	-
	> Rambox 0.7.3
	> Electron 7.1.1
	> win32 x64 10.0.18362

**Comment by fvulich** [comment] 2020-01-17 13:36
Could you try doing a Clear Cache and a Clear Local Storage and then restart Rambox?
![image](https://user-images.githubusercontent.com/46904390/72616222-34bb2d80-3915-11ea-8b80-7874a9cac02f.png)

If that doesn't work you could try doing a uninstall following this tutorial
[Clean Uninstall](https://github.com/ramboxapp/community-edition/wiki/Clean-Uninstall)

And then download the latest Rambox version from [HERE](https://github.com/ramboxapp/community-edition/releases/latest)

And installing it again. If this doesn't work, please contact us, so we could give you more help.

**Comment by User991** [comment] 2020-01-17 13:54
Hi,
i've done all the steps you have suggested, but the error still displays at
each movement of the window on the screen.

Il giorno ven 17 gen 2020 alle ore 14:36 Vulich Fernando <
notifications@github.com> ha scritto:

**Comment by fvulich** [comment] 2020-01-17 13:56
Which Windows version are you using?

**Comment by User991** [comment] 2020-01-17 13:59
i am using this one:
[image: image.png]

Il giorno ven 17 gen 2020 alle ore 14:56 Vulich Fernando <
notifications@github.com> ha scritto:

**Comment by fvulich** [comment] 2020-01-17 14:05
The image is not loading.

**Comment by User991** [comment] 2020-01-17 14:25
Windows 10, Version: 1903, OS Build: 18362.592

Il giorno ven 17 gen 2020 alle ore 15:05 Vulich Fernando <
notifications@github.com> ha scritto:

**Comment by fvulich** [comment] 2020-01-17 14:32
Ok, I couldn't reproduce the issue. Could you try it in other device?

**Comment by User991** [comment] 2020-01-17 14:36
not now.
I'll let you know when i can try on another pc.

Il giorno ven 17 gen 2020 alle ore 15:32 Vulich Fernando <
notifications@github.com> ha scritto:

**Comment by fvulich** [comment] 2020-01-31 16:54
We haven't received a response to our question in this ticket. With only the information that is currently in the ticket, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by fvulich** 2020-01-31 16:54 UTC
Labels: investigate, more-information-needed, windows
